### PR TITLE
Add a Pidgin snap

### PR DESCRIPTION
**Pull request by tsimonq2**
This adds a Pidgin snap. It's more of a work in progress, but it's at a point where I would like feedback as to how I can improve this.

---

This change is [Reviewable](https://reviewable.io/reviews/ubuntu/snappy-playpen/62)

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/ubuntu/snappy-playpen/pull/62%23issuecomment-226133823%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/62%23issuecomment-226151173%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/62%23issuecomment-226157677%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/62%23issuecomment-226157882%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/62%23issuecomment-226161717%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/62%23issuecomment-227386868%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/62%23issuecomment-227387947%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/62%23issuecomment-227393720%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/62%23issuecomment-227393769%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/62%23issuecomment-227394809%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/62%23issuecomment-227395380%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/62%23issuecomment-227401246%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/62%23issuecomment-226133823%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Fails%20to%20build%3A%20http%3A//paste.ubuntu.com/17354342/%22%2C%20%22created_at%22%3A%20%222016-06-15T09%3A20%3A47Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40dholbach%20it%27s%20fine%20now%2C%20can%20you%20run%20it%20again%3F%22%2C%20%22created_at%22%3A%20%222016-06-15T10%3A39%3A53Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3689821%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tsimonq2%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20get%5Cr%5Cn%60%60%60%5Cr%5CnFailed%20to%20load%20selected%20keyring.%5Cr%5Cn%5Cr%5CnCheck%20your%20system%20configuration%20or%20select%20another%20one%20in%20Preferences%20dialog%5Cr%5Cn%60%60%60%5Cr%5Cn%5Cr%5CnAnd%20can%27t%20add%20accounts.%22%2C%20%22created_at%22%3A%20%222016-06-15T11%3A13%3A00Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20wouldn%27t%20use%20%3Awhite_check_mark%3A%20in%20this%20case.%20It%27d%20be%20good%20if%20we%20could%20get%20at%20least%20one%20or%20two%20plugins%20to%20compile.%22%2C%20%22created_at%22%3A%20%222016-06-15T11%3A14%3A03Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40dholbach%20I%27ve%20added%20gnome-keyring%20to%20stage-packages%2C%20the%20library%20is%20in%20build-packages%2C%20I%27m%20building%20now%2C%20then%20hopefully%20it%20will%20work%20fine.%22%2C%20%22created_at%22%3A%20%222016-06-15T11%3A34%3A08Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3689821%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tsimonq2%22%7D%7D%2C%20%7B%22body%22%3A%20%22Can%20you%20bring%20up%20the%20problem%20of%20compiling%20the%20plugins%20on%20the%20mailing%20list%20and%20seek%20help%20there%3F%20I%20think%20%60pidgin%60%20would%20be%20fantastic%20in%20the%20Playpen%2C%20but%20we%20should%20at%20least%20have%20a%20few%20plugins%20working.%5Cn%5Cn---%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/62%23-%3A-KKmGA6p48GKu0Bk0pcQ%3A1861010157%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-06-21T09%3A23%3A18Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40dholbach%20What%20plugins%20are%20you%20talking%20about%3F%22%2C%20%22created_at%22%3A%20%222016-06-21T09%3A27%3A52Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3689821%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tsimonq2%22%7D%7D%2C%20%7B%22body%22%3A%20%22At%20the%20very%20very%20least%20Jabber%2C%20maybe%20some%20others%20too%3F%20Or%20are%20they%20not%20included%20in%20the%20source%3F%5Cn%5Cn---%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/62%23-%3A-KKmN14PpxIR_Xj77au9%3A-477424036%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-06-21T09%3A53%3A00Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%5Cn%5Cn%5CnReviewed%201%20of%203%20files%20at%20r1%2C%201%20of%201%20files%20at%20r4%2C%201%20of%201%20files%20at%20r5.%5CnReview%20status%3A%20all%20files%20reviewed%20at%20latest%20revision%2C%20all%20discussions%20resolved.%5Cn%5Cn---%5Cn%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/62%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-06-21T09%3A53%3A11Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%2A%5Bpidgin/README.md%2C%20line%209%20%5C%5C%5Br5%5C%5C%5D%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/62%23-KKmOA5OFpOcKsqHg_hm%3A-KKmOA5PAAgl5-V_zbkv%3A432399498%29%20%28%5Braw%20file%5D%28https%3A//github.com/ubuntu/snappy-playpen/blob/8c57f78ad43abaa97f091894bc5a72be48c8e526/pidgin/README.md%23L9%29%29%3A%2A%5Cn%3E%20%60%60%60Markdown%5Cn%3E%20%23%23%20Current%20state%5Cn%3E%20%5Cn%3E%20Everything%20should%20be%20working%20except%20plugin%20support%2C%20I%20couldn%27t%20get%20that%20to%20compile.%5Cn%3E%20%60%60%60%5Cn%5CnIt%27d%20be%20nice%20if%20we%20could%20get%20some%20plugins%20to%20build.%5Cn%5Cn---%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/62%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-06-21T09%3A57%3A52Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40dholbach%20I%27ll%20remove%20the%20build%20flag%20that%20disables%20them%2C%20let%27s%20see%20what%20breaks%20%3Afire%3A%20%3Adash%3A%22%2C%20%22created_at%22%3A%20%222016-06-21T10%3A00%3A31Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3689821%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tsimonq2%22%7D%7D%2C%20%7B%22body%22%3A%20%22Let%20us%20know%20if%20this%20really%20works.%20This%20needs%20testing%20before%20it%27s%20reviewed.%5Cn%5Cn---%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/62%23-%3A-KKmV36banLfVP3BipVs%3A1065828245%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-06-21T10%3A28%3A13Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/ubuntu/snappy-playpen/pull/62#issuecomment-226133823'>General Comment</a></b>
- <a href='https://github.com/dholbach'></a> Fails to build: http://paste.ubuntu.com/17354342/
- <a href='https://github.com/tsimonq2'></a> @dholbach it's fine now, can you run it again?
- <a href='https://github.com/dholbach'></a> I get

```
Failed to load selected keyring.
Check your system configuration or select another one in Preferences dialog
```

And can't add accounts.
- <a href='https://github.com/dholbach'></a> I wouldn't use :white_check_mark: in this case. It'd be good if we could get at least one or two plugins to compile.
- <a href='https://github.com/tsimonq2'></a> @dholbach I've added gnome-keyring to stage-packages, the library is in build-packages, I'm building now, then hopefully it will work fine.
## \- <a href='https://github.com/dholbach'></a> Can you bring up the problem of compiling the plugins on the mailing list and seek help there? I think `pidgin` would be fantastic in the Playpen, but we should at least have a few plugins working.

_Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/62#-:-KKmGA6p48GKu0Bk0pcQ:1861010157)_

- <a href='https://github.com/tsimonq2'></a> @dholbach What plugins are you talking about?
## \- <a href='https://github.com/dholbach'></a> At the very very least Jabber, maybe some others too? Or are they not included in the source?

_Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/62#-:-KKmN14PpxIR_Xj77au9:-477424036)_

- <a href='https://github.com/dholbach'></a> Reviewed 1 of 3 files at r1, 1 of 1 files at r4, 1 of 1 files at r5.
  Review status: all files reviewed at latest revision, all discussions resolved.
  ---
  _Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/62)_
  
- <a href='https://github.com/dholbach'></a> _[pidgin/README.md, line 9 [r5]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/62#-KKmOA5OFpOcKsqHg_hm:-KKmOA5PAAgl5-V_zbkv:432399498) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/8c57f78ad43abaa97f091894bc5a72be48c8e526/pidgin/README.md#L9)):_
  > `Markdown
  > ## Current state
  >
  > Everything should be working except plugin support, I couldn't get that to compile.
  >`
  It'd be nice if we could get some plugins to build.
  ---
  _Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/62)_
  
- <a href='https://github.com/tsimonq2'></a> @dholbach I'll remove the build flag that disables them, let's see what breaks :fire: :dash:
## \- <a href='https://github.com/dholbach'></a> Let us know if this really works. This needs testing before it's reviewed.

_Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/62#-:-KKmV36banLfVP3BipVs:1065828245)_

<a href='https://www.codereviewhub.com/ubuntu/snappy-playpen/pull/62?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/ubuntu/snappy-playpen/pull/62?approve=1'></a>&nbsp;<a href='https://github.com/ubuntu/snappy-playpen/pull/62'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dholbach** [comment]
Fails to build: http://paste.ubuntu.com/17354342/

**Comment by tsimonq2** [comment]
@dholbach it's fine now, can you run it again?

**Comment by dholbach** [comment]
I get
```
Failed to load selected keyring.

Check your system configuration or select another one in Preferences dialog
```

And can't add accounts.

**Comment by dholbach** [comment]
I wouldn't use :white_check_mark: in this case. It'd be good if we could get at least one or two plugins to compile.

**Comment by tsimonq2** [comment]
@dholbach I've added gnome-keyring to stage-packages, the library is in build-packages, I'm building now, then hopefully it will work fine.

**Comment by dholbach** [comment]
Can you bring up the problem of compiling the plugins on the mailing list and seek help there? I think `pidgin` would be fantastic in the Playpen, but we should at least have a few plugins working.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/62#-:-KKmGA6p48GKu0Bk0pcQ:1861010157)*

**Comment by tsimonq2** [comment]
@dholbach What plugins are you talking about?

**Comment by dholbach** [comment]
At the very very least Jabber, maybe some others too? Or are they not included in the source?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/62#-:-KKmN14PpxIR_Xj77au9:-477424036)*

**Comment by dholbach** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/62)*

**Comment by dholbach** [comment]
*[pidgin/README.md, line 9 \[r5\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/62#-KKmOA5OFpOcKsqHg_hm:-KKmOA5PAAgl5-V_zbkv:432399498) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/8c57f78ad43abaa97f091894bc5a72be48c8e526/pidgin/README.md#L9)):*
> ```Markdown
> ## Current state
> 
> Everything should be working except plugin support, I couldn't get that to compile.
> ```

It'd be nice if we could get some plugins to build.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/62)*

**Comment by tsimonq2** [comment]
@dholbach I'll remove the build flag that disables them, let's see what breaks :fire: :dash:

**Comment by dholbach** [comment]
Let us know if this really works. This needs testing before it's reviewed.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/62#-:-KKmV36banLfVP3BipVs:1065828245)*

**Pull request closed without merging**
