### PR TITLE
Ffmpeg patch

### PR DESCRIPTION
**Pull request by wandrewkeech**
This PR updates `ffmpeg` to build the base binary, works great and everything.

---
This change is [Reviewable](https://reviewable.io/reviews/ubuntu/snappy-playpen/94)

### CODE REVIEW

**Comment by dholbach** [comment]
*[ffmpeg/README.md, line 12 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/94#-KKmX1ROLD7BAhOJfJqx:-KKmX1RQQX_9P_xIkgqa:1143630169) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/2024fe9aceded7fc12de08687bc924322620a706/ffmpeg/README.md#L12)):*
> ```Markdown
> Working features:
>  - `ffmpeg`, accessed through `ffmpeg.convert` once installed.
> ```

Why is this necessary?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/94)*

**Comment by dholbach** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/94#-:-KKr3-AEbpBqcCONzMqB:1417088721)*

**Comment by dholbach** [comment]
Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/94)*

**Comment by dholbach** [comment]
:lgtm_cancel: Sorry, looks like the branch has conflicts. Please resolve them and we should be good to go.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/94#-:-KKr3LDBTW1YFZiK_NdI:1584236165)*

**Comment by didrocks** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[ffmpeg/snapcraft.yaml, line 36 \[r3\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/94#-KKrSV8VDAcU48QV3qVG:-KKrSV8VDAcU48QV3qVH:1358603635) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/ac4cfed42b5a277a588dc0897cd865d7a7caa376/ffmpeg/snapcraft.yaml#L36)):*
> ```YAML
> 
> parts:
> ```

It seems there is an extra line break here (or maybe it's the output?)

---

*[ffmpeg/snapcraft.yaml, line 83 \[r3\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/94#-KKrSKa_FDTafkO3ClJm:-KKrSKa_FDTafkO3ClJn:353342066) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/ac4cfed42b5a277a588dc0897cd865d7a7caa376/ffmpeg/snapcraft.yaml#L83)):*
> ```YAML
>       - yasm
>       - zlib1g-dev
>     organize:
> ```

From the guideline, we did put organize and such keywords before build-packages, mind moving it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/94)*

**Comment by didrocks** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[ffmpeg/snapcraft.yaml, line 36 \[r3\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/94#-KKrSV8VDAcU48QV3qVG:-KKrVWBEqhxT2_v9tbfM:676834233) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/ac4cfed42b5a277a588dc0897cd865d7a7caa376/ffmpeg/snapcraft.yaml#L36)):*
<details><summary><i>Previously, didrocks (Didier Roche) wrote…</i></summary>
> It seems there is an extra line break here (or maybe it's the output?)
</details>
LGTM

---

*[ffmpeg/snapcraft.yaml, line 83 \[r3\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/94#-KKrSKa_FDTafkO3ClJm:-KKrVNuqY9R2R2QGxlpx:1034815308) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/ac4cfed42b5a277a588dc0897cd865d7a7caa376/ffmpeg/snapcraft.yaml#L83)):*
<details><summary><i>Previously, didrocks (Didier Roche) wrote…</i></summary>
> From the guideline, we did put organize and such keywords before build-packages, mind moving it?
</details>
Thanks for fixing it!

---

*[ffmpeg/snapcraft.yaml, line 19 \[r4\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/94#-KKrVeExtW1i3giocLT-:-KKrVeExtW1i3giocLT0:-1119138315) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/cd1742ffa861e68097125a93f78f9565e576ed25/ffmpeg/snapcraft.yaml#L19)):*
> ```YAML
> 
> apps:
>   convert:
> ```

As discussed on gitter, I would just use the ffmepg app name here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/94)*

**Comment by didrocks** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/94)*

**Comment by wandrewkeech** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[ffmpeg/snapcraft.yaml, line 19 \[r4\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/94#-KKrVeExtW1i3giocLT-:-KKsTY26HhU0rgGafD6Z:-499146009) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/cd1742ffa861e68097125a93f78f9565e576ed25/ffmpeg/snapcraft.yaml#L19)):*
<details><summary><i>Previously, didrocks (Didier Roche) wrote…</i></summary>
> As discussed on gitter, I would just use the ffmepg app name here
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/94)*

**Comment by dholbach** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/94#-:-KKsiNQIhUaY7xPo0Zru:1417088721)*

**Comment by dholbach** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/94)*

**Pull request merged**
