### PR TITLE
JavaFX Modena Sample Application using OpenJDK and OpenJFX

### PR DESCRIPTION
**Pull request by rednoah**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/ubuntu/snappy-playpen/pull/201%23issuecomment-238465806%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/201%23issuecomment-238465940%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/201%23issuecomment-238466362%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/201%23issuecomment-238471080%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/201%23issuecomment-238474526%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/201%23issuecomment-238465806%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Could%20this%20.jar%20file%20be%20obtained%20from%20somewhere%20else%20during%20the%20build%2C%20so%20we%20don%27t%20need%20to%20ship%20it%20in%20the%20Playpen%20repo%3F%22%2C%20%22created_at%22%3A%20%222016-08-09T06%3A33%3A34Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%2C%20%7B%22body%22%3A%20%22Can%20you%20add%20a%20%60./openjfx-modena/README.md%60%20file%20based%20on%20%60./snap-template/README.md%60%3F%22%2C%20%22created_at%22%3A%20%222016-08-09T06%3A34%3A27Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%2C%20%7B%22body%22%3A%20%22It%20looks%20like%20the%20%5Bhttps%3A//travis-ci.org/ubuntu/snappy-playpen/builds/149438047%5D%28CI%20build%29%20failed%20due%20to%20%5Bhttps%3A//bugs.launchpad.net/snapcraft/%2Bbug/1607015%5D%28bug%201607015%29.%20I%20just%20asked%20what%20the%20recommended%20next%20steps%20are.%22%2C%20%22created_at%22%3A%20%222016-08-09T06%3A37%3A16Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%2C%20%7B%22body%22%3A%20%22Unfortunately%2C%20the%20jar%20and%20the%20source%20code%20is%20part%20of%20the%20%5BJava%20SE%20Development%20Kit%208u102%20Demos%20and%20Samples%20Downloads%5D%28http%3A//www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html%29%20%2850%20MB%29.%20I%27ll%20see%20if%20I%20can%20find%20a%20source%20repository%20or%20jars%20on%20maven%20central.%22%2C%20%22created_at%22%3A%20%222016-08-09T07%3A05%3A16Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1589068%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/rednoah%22%7D%7D%2C%20%7B%22body%22%3A%20%22-%20Added%20%60README.md%60%20file%22%2C%20%22created_at%22%3A%20%222016-08-09T07%3A24%3A56Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1589068%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/rednoah%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/ubuntu/snappy-playpen/pull/201#issuecomment-238465806'>General Comment</a></b>
- <a href='https://github.com/dholbach'></a> Could this .jar file be obtained from somewhere else during the build, so we don't need to ship it in the Playpen repo?
- <a href='https://github.com/dholbach'></a> Can you add a `./openjfx-modena/README.md` file based on `./snap-template/README.md`?
- <a href='https://github.com/dholbach'></a> It looks like the [https://travis-ci.org/ubuntu/snappy-playpen/builds/149438047](CI build) failed due to [https://bugs.launchpad.net/snapcraft/+bug/1607015](bug 1607015). I just asked what the recommended next steps are.
- <a href='https://github.com/rednoah'></a> Unfortunately, the jar and the source code is part of the [Java SE Development Kit 8u102 Demos and Samples Downloads](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html) (50 MB). I'll see if I can find a source repository or jars on maven central.
- <a href='https://github.com/rednoah'></a> - Added `README.md` file

<a href='https://www.codereviewhub.com/ubuntu/snappy-playpen/pull/201?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/ubuntu/snappy-playpen/pull/201?approve=1'></a>&nbsp;<a href='https://github.com/ubuntu/snappy-playpen/pull/201'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by didrocks** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/ubuntu/snappy-playpen/pull/201'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by dholbach** [comment]
Could this .jar file be obtained from somewhere else during the build, so we don't need to ship it in the Playpen repo?

**Comment by dholbach** [comment]
Can you add a `./openjfx-modena/README.md` file based on `./snap-template/README.md`?

**Comment by dholbach** [comment]
It looks like the [https://travis-ci.org/ubuntu/snappy-playpen/builds/149438047](CI build) failed due to [https://bugs.launchpad.net/snapcraft/+bug/1607015](bug 1607015). I just asked what the recommended next steps are.

**Comment by rednoah** [comment]
Unfortunately, the jar and the source code is part of the [Java SE Development Kit 8u102 Demos and Samples Downloads](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html) (50 MB). I'll see if I can find a source repository or jars on maven central.

**Comment by rednoah** [comment]
- Added `README.md` file

**Pull request closed without merging**
