### PR TITLE
add gitter.im branch

### PR DESCRIPTION
**Pull request by ogra1**
This change is [Reviewable](https://reviewable.io/reviews/ubuntu/snappy-playpen/97)

### CODE REVIEW

**Comment by didrocks** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[gitter-im/snapcraft.yaml, line 2 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/97#-KKmciGpF2YqGeXSXeF7:-KKmciGpF2YqGeXSXeF8:1713790198) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/22b788e4f6a1b6055c6f9f3e01c843f829bcd662/gitter-im/snapcraft.yaml#L2)):*
> ```YAML
> name: gitter
> version: 3.0.3-1
> ```

Please use "" or '' around version: as per playpen guidelines requirements (http://pad.ubuntu.com/UIHBM858kK).

---

*[gitter-im/snapcraft.yaml, line 9 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/97#-KKmcp82xF7ws2lwFYNX:-KKmcp82xF7ws2lwFYNY:-1613538904) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/22b788e4f6a1b6055c6f9f3e01c843f829bcd662/gitter-im/snapcraft.yaml#L9)):*
> ```YAML
> apps:
>   gitter:
>     command: gtk-launch ./Gitter
> ```

Do you really need ./Gitter in front of gtk-launch, can it work without this?

---

*[gitter-im/snapcraft.yaml, line 22 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/97#-KKmcyZa6CVihVB6_ijL:-KKmcyZa6CVihVB6_ijM:1332761782) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/22b788e4f6a1b6055c6f9f3e01c843f829bcd662/gitter-im/snapcraft.yaml#L22)):*
> ```YAML
>       - libnss3
>       - ttf-ubuntu-font-family
>     after: [gtkconf, download]
> ```

As this part is after: download, please put download before this one.

---

*[gitter-im/snapcraft.yaml, line 31 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/97#-KKmd3b0e2JQByZHADNn:-KKmd3b0e2JQByZHADNo:1332761782) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/22b788e4f6a1b6055c6f9f3e01c843f829bcd662/gitter-im/snapcraft.yaml#L31)):*
> ```YAML
>       icudtl.dat: icudtl.dat
>       libffmpegsumo.so: libffmpegsumo.so
>     after: [download]
> ```

As this part is after: download, please put download before this one.

---

*[gitter-im/snapcraft.yaml, line 34 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/97#-KKmd78tkDBnztlDydi0:-KKmd78tkDBnztlDydi1:1964515205) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/22b788e4f6a1b6055c6f9f3e01c843f829bcd662/gitter-im/snapcraft.yaml#L34)):*
> ```YAML
>   download:
>     plugin: make
>     source: .
> ```

source should be before plugin as per our playpen guidelines requirements.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/97)*

**Comment by dholbach** [comment]
*[gitter-im/snapcraft.yaml, line 34 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/97#-KKmd78tkDBnztlDydi0:-KKmeKJt5TCr6x3a-xjv:466766251) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/22b788e4f6a1b6055c6f9f3e01c843f829bcd662/gitter-im/snapcraft.yaml#L34)):*
<details><summary><i>Previously, didrocks (Didier Roche) wrote…</i></summary>
> source should be before plugin as per our playpen guidelines requirements.
</details>
I guess this needs `wget` as `build-packages`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/97)*

**Comment by ogra1** [comment]
i think i adressed all bits apart from the question about gtk-launch ... the app is a Chromium based binary, gtk-launch makes sure the execution environment is correct so pango fonts are found etc.

**Comment by dplanella** [comment]
Review status: 1 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[gitter-im/snapcraft.yaml, line 9 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/97#-KKmcp82xF7ws2lwFYNX:-KKmkzEMXtvkyhz9Nwh_:1062153886) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/22b788e4f6a1b6055c6f9f3e01c843f829bcd662/gitter-im/snapcraft.yaml#L9)):*
<details><summary><i>Previously, didrocks (Didier Roche) wrote…</i></summary>
> Do you really need ./Gitter in front of gtk-launch, can it work without this?
</details>
I guess the question is more about the `./` perhaps. But if not, `gtk-launch` needs the name of the binary to be executed. It is simply a wrapper that sets up the environment variables, generates the GSettings schemas, etc, and ultimately calls the binary passed on to it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/97)*

**Comment by dplanella** [comment]
Review status: 1 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[gitter-im/snapcraft.yaml, line 31 \[r2\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/97#-KKmmf44XvzZyKSga24J:-KKmmf44XvzZyKSga24K:-1077980805) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/7cf03c98fe843e64afb1adc76299b0760d79eec9/gitter-im/snapcraft.yaml#L31)):*
> ```YAML
>       - libgl1-mesa-glx
>       - libglib2.0-0
>       - libgtk-3-0
> ```

I think you might need `libgtk-3-bin` too, which contains the `update-icon-caches` binary that `gtk-launch` uses

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/97)*

**Comment by ogra1** [comment]
*[gitter-im/snapcraft.yaml, line 31 \[r2\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/97#-KKmmf44XvzZyKSga24J:-KKmqDXZJGcT7IjHDV5j:-742847959) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/7cf03c98fe843e64afb1adc76299b0760d79eec9/gitter-im/snapcraft.yaml#L31)):*
<details><summary><i>Previously, dplanella (David Planella) wrote…</i></summary>
> I think you might need `libgtk-3-bin` too, which contains the `update-icon-caches` binary that `gtk-launch` uses
</details>
libgtk-3-bin is a dependency of libgtk-3-0

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/97)*

**Comment by dholbach** [comment]
*[gitter-im/snapcraft.yaml, line 31 \[r2\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/97#-KKmmf44XvzZyKSga24J:-KKmrfy1uhzlm6qdhq2a:635181839) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/7cf03c98fe843e64afb1adc76299b0760d79eec9/gitter-im/snapcraft.yaml#L31)):*
<details><summary><i>Previously, ogra1 wrote…</i></summary>
> libgtk-3-bin is a dependency of libgtk-3-0
</details>
I don't think that's how `stage-packages` works. Does it pull in all dependencies and extracts all of them?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/97)*

**Comment by ogra1** [comment]
*[gitter-im/snapcraft.yaml, line 31 \[r2\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/97#-KKmmf44XvzZyKSga24J:-KKmtPpK3B0DSvUrnlSh:-430461648) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/7cf03c98fe843e64afb1adc76299b0760d79eec9/gitter-im/snapcraft.yaml#L31)):*
<details><summary><i>Previously, dholbach (Daniel Holbach) wrote…</i></summary>
> I don't think that's how `stage-packages` works. Does it pull in all dependencies and extracts all of them?
</details>
well, it pulls the lib during build according to the build logs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/97)*

**Comment by didrocks** [comment]
Reviewed 1 of 3 files at r1, 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[gitter-im/snapcraft.yaml, line 9 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/97#-KKmcp82xF7ws2lwFYNX:-KKnA5AgIs_X0kOm2EqV:5173665) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/22b788e4f6a1b6055c6f9f3e01c843f829bcd662/gitter-im/snapcraft.yaml#L9)):*
<details><summary><i>Previously, dplanella (David Planella) wrote…</i></summary>
> I guess the question is more about the `./` perhaps. But if not, `gtk-launch` needs the name of the binary to be executed. It is simply a wrapper that sets up the environment variables, generates the GSettings schemas, etc, and ultimately calls the binary passed on to it.
</details>
OK

---

*[gitter-im/snapcraft.yaml, line 31 \[r2\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/97#-KKmmf44XvzZyKSga24J:-KKnATx2h5SOpVcDt5UH:676834233) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/7cf03c98fe843e64afb1adc76299b0760d79eec9/gitter-im/snapcraft.yaml#L31)):*
<details><summary><i>Previously, ogra1 wrote…</i></summary>
> well, it pulls the lib during build according to the build logs
</details>
LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/97)*

**Comment by didrocks** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/97)*

**Comment by didrocks** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[gitter-im/snapcraft.yaml, line 31 \[r2\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/97#-KKmmf44XvzZyKSga24J:-KKnC0wo0kwsvbFambNb:5173665) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/7cf03c98fe843e64afb1adc76299b0760d79eec9/gitter-im/snapcraft.yaml#L31)):*
<details><summary><i>Previously, didrocks (Didier Roche) wrote…</i></summary>
> LGTM
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/97)*

**Comment by didrocks** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/97)*

**Pull request merged**
