### PR TITLE
Add Residualvm

### PR DESCRIPTION
**Pull request by LyzardKing**
This was a test to check the opengl status.
Unfortunately for me it works only if I set it to use the software rendering.
I'm not sure if it's an issue with the nvidia driver and snappy or if the snap has something missing.
(It starts only if installed with -devmode)

---
This change is [Reviewable](https://reviewable.io/reviews/ubuntu/snappy-playpen/159)

### CODE REVIEW

**Comment by dholbach** [comment]
It looks like there are merge conflicts - can you rebase on current master?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/159#-:-KMYjXs3qiosG767CjAX:-129487087)*

**Comment by dholbach** [comment]
*[residualvm/README.md, line 15 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/159#-KMYjkMW1NnBfjEijD8N:-KMYjkMW1NnBfjEijD8O:1330167606) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/bcd1f85248509b7b9efbd9f9d0893f17f4c00e56/residualvm/README.md#L15)):*
> ```Markdown
> Known issues:
>   - No theme for the main UI
>   - Has to be installed with devmode
> ```

Are there apparmor/seccomp denials you are aware of? (`snappy-debug.security scanlog` should know.) If yes, it'd be good to file some bugs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/159)*

**Comment by LyzardKing** [comment]
The conflicts were in the main README file. It should work now.
I'll check the scanlog now.

**Comment by LyzardKing** [comment]
Ok, I was missing unity7. With that added it works (again, not in opengl mode)

**Comment by dholbach** [comment]
The branch currently conflicts with master, can you rebase?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/159#-:-KMdduAtNtKrwZjzFftB:2130116541)*

**Comment by dholbach** [comment]
:lgtm:  - can we note down somewhere what the issues with `devmode` are? Are there apparmor/seccomp denials?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/159#-:-KMiVHC9crJNG7KEkJPo:-573517693)*

**Comment by dholbach** [comment]
Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/159)*

**Comment by LyzardKing** [comment]
@dholbach Apparently it now works without devmode.. Not sure why.. The only issues remaining are the opengl one and the missing theme

**Comment by dholbach** [comment]
Cool - do you want to push a follow-up PR for this?

**Comment by LyzardKing** [comment]
The only thing that needs changing is the README. The rest is already up to date. Should I add a pr?

**Comment by dholbach** [comment]
No change to `snapcraft.yaml` to change the confinement setting too?

**Comment by LyzardKing** [comment]
No, that's what's strange. It used to not start, and basically freeze a terminal. Now it starts...I tried removing it and installing with no previous settings and it works... The problem could have been some wrong settings remaining from a previous install..

**Comment by LyzardKing** [comment]
It starts with no error/warning in the debug scanlog

**Comment by dholbach** [comment]
Ok, cool. Feel free to send a PR for the README change then.

**Pull request merged**
