### PR TITLE
Add Nikola.

### PR DESCRIPTION
**Pull request by flexiondotorg**
This pull request add the static site generator, Nikola.

  * https://gitnikola.com

This snap builds, but `nikola` fails to execute. See the include README.md for how to simply reproduce the error. Any help solving this is greatly appreciated :-)

---
This change is [Reviewable](https://reviewable.io/reviews/ubuntu/snappy-playpen/72)

### CODE REVIEW

**Comment by dholbach** [comment]
Do you get something like this too? http://paste.ubuntu.com/17590013/

**Comment by dholbach** [comment]
Putting this on hold for now.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/72#-:-KKmLrgG6kfh6tClbw7O:1816768425)*

**Comment by dholbach** [comment]
*[README.md, line 29 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/72#-KKmMdnAmpzX6_aNiBVM:-KKmMdnBIlZD_m2xYzsy:-1734252183) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/681dfe9370a3abe31b87f8e1e86a8270835bde4f/README.md#L29)):*
> ```Markdown
> | :white_check_mark:  | `moon-buggy`       | [moon-buggy][moon-buggy]  |
> | :white_check_mark:  | `mpv`              |                           |
> | :white_check_mark:  | `nikola`           |                           |
> ```

Maybe change it here for now? And bring it up on the ML?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/72)*

**Comment by ralsina** [comment]
I merged an initial snap packaging in Nikola's repo a few days ago:

https://github.com/getnikola/nikola/tree/master/snapcraft

There are a few things that don't work (and probably never will) like nikola deploy or the -b option in nikola serve and nikola auto, but the basics are there.

**Comment by dplanella** [comment]
Closed as per Roberto's comment

**Comment by flexiondotorg** [comment]
I've spoken to @ralsina in IRC and will contribute to the upstream snap.

**Pull request closed without merging**
