### PR TITLE
Ubuntukylin icon theme

### PR DESCRIPTION
**Pull request by fcole90**
Added support for the ubuntukylin-icon-theme

### CODE REVIEW

**Comment by caldav** [comment]
Hi Fabio, that's an big branch you have there :) I really like the ideas behind this snap but do you think your branch could pull the theme from source instead of shipping it along the snapcraft.yaml?

eg.
```
 plugin: copy
 source: lp:ubuntukylin-theme
 source-type: bzr
```

**Comment by fcole90** [comment]
It's a very good idea indeed. But will then be possible to choose only the
required folders?
In addition there's a problem because I renamed the theme (just adding the
suffix '-snap') to avoid users having two entries with the same name in
their theme manager. Do you think is it worth to avoid such name clash in
this scenario? And if yes, would it be still possible to rename the theme
before packaging? :)

On 7 June 2016 at 16:00, David Callé <notifications@github.com> wrote:

> Hi Fabio, that's an big branch you have there :) I really like the ideas
> behind this snap but do you think your branch could pull the theme from
> source instead of shipping it along the snapcraft.yaml?
>
> eg.
>
>  plugin: copy
>  source: lp:ubuntukylin-theme
>  source-type: bzr
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ubuntu/snappy-playpen/pull/38#issuecomment-224289415>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABO3xlMwdE570qNQlgijqX1xmGZ8aADKks5qJXmXgaJpZM4Iv7X2>
> .
>



-- 
Your sincerely,
Fabio Colella


Prova un Sistema di Nuova Generazione,
<http://www.ubuntu-it.org/scopri-ubuntu>
*GRATIS Per Sempre! <http://www.ubuntu-it.org/scopri-ubuntu> Server, PC,
mobile, IoT <https://developer.ubuntu.com/en/start/ubuntu-for-devices/>*

prova Ubuntu ORA e Migliora le Performance del tuo PC!
<http://www.ubuntu-it.org/scopri-ubuntu>
IT <http://www.ubuntu-it.org/> - EN <http://www.ubuntu.com/>

**Comment by caldav** [comment]
Picking only a specific folder is easy with the "files" and "organize" directives of the copy plugin. The edit part is trickier as it requires a custom plugin. 

Here is an example plugin that will do it for you, I simply re-used the edit plugin and added regex powers to it: https://gist.github.com/caldav/9f0978ef0aa4cda6d4cdf92fced1e99b

It was quite easy to make, changes to the original plugin are at l58-60 and l83-89
See the comment on the gist for a sample snapcraft.yaml using it.

**Comment by fcole90** [comment]
Thank you, I'm gonna try it ;)

**Comment by fcole90** [comment]
@caldav Thank you very much for your help!

**Pull request merged**
