### PR TITLE
Added a Sylpheed snap

### PR DESCRIPTION
**Pull request by tsimonq2**
This adds a Sylpheed snap that uses Subversion, support for which is pending in Snapcraft.

It works fine on a generic Ubuntu install.

---

This change is [Reviewable](https://reviewable.io/reviews/ubuntu/snappy-playpen/60)

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/ubuntu/snappy-playpen/pull/60%23issuecomment-225932282%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/60%23issuecomment-225935456%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/60%23issuecomment-225938627%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/60%23issuecomment-227403458%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/60%23issuecomment-227403728%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/60%23issuecomment-227920239%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/60%23issuecomment-227958319%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/60%23issuecomment-230314766%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/60%23issuecomment-230395914%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/60%23issuecomment-230395956%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/60%23issuecomment-225932282%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22E%3A%20Failed%20to%20fetch%20http%3A//archive.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_4.4.0-22.40_amd64.deb%20%20404%20%20Not%20Found%20%5BIP%3A%2091.189.88.152%2080%5D%20-%20I%20feel%20like%20this%20isn%27t%20something%20I%20control...%22%2C%20%22created_at%22%3A%20%222016-06-14T16%3A10%3A07Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3689821%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tsimonq2%22%7D%7D%2C%20%7B%22body%22%3A%20%22Thanks%20Simon%20for%20the%20pull%20request%21%20Instead%20of%20adding%20a%20new%20copy%20of%20the%20wrapper%2C%20would%20you%20mind%20using%20the%20%60gtkconf%60%20wiki%20part%20as%20%5BLeafpad%5D%28https%3A//github.com/ubuntu/snappy-playpen/blob/master/leafpad/snapcraft.yaml%29%20and%20%5BRistretto%5D%28https%3A//github.com/ubuntu/snappy-playpen/blob/master/ristretto/snapcraft.yaml%23L39%29%20do%3F%5Cr%5Cn%5Cr%5CnEssentially%2C%20it%27s%20about%3A%5Cr%5Cn-%20Removing%20the%20custom%20wrapper%5Cr%5Cn-%20Modifying%20snapcraft.yaml%20to%3A%5Cr%5Cn%20%20-%20Set%20the%20command%20to%20be%20%60gtk-launch%20sylpheed%60%5Cr%5Cn%20%20-%20Add%20the%20%60gtkconf%60%20wiki%20part%5Cr%5Cn%20%20-%20Add%20either%20%60libgtk2.0-bin%60%20or%20%60libgtk-3-0-bin%60%20to%20%60stage-packages%60%22%2C%20%22created_at%22%3A%20%222016-06-14T16%3A20%3A43Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1689781%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dplanella%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40dplanella%20Will%20do%2C%20thanks%20for%20the%20feedback%21%22%2C%20%22created_at%22%3A%20%222016-06-14T16%3A31%3A25Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3689821%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tsimonq2%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%2A%5Bsylpheed/snapcraft.yaml%2C%20line%2015%20%5C%5C%5Br2%5C%5C%5D%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/60%23-KKmXkuMTXmPCq5khNFI%3A-KKmXkuNIYof7Nw6nqgx%3A1185909849%29%20%28%5Braw%20file%5D%28https%3A//github.com/ubuntu/snappy-playpen/blob/95b063a13885d1d26b58ffeec795c16e0ba8bb57/sylpheed/snapcraft.yaml%23L15%29%29%3A%2A%5Cn%3E%20%60%60%60YAML%5Cn%3E%20%20%20%20%20sylpheed%3A%5Cn%3E%20%20%20%20%20%20%20%20%20plugin%3A%20autotools%5Cn%3E%20%20%20%20%20%20%20%20%20source%3A%20svn%3A//sylpheed.sraoss.jp/sylpheed/trunk%5Cn%3E%20%60%60%60%5Cn%5CnWe%20are%20still%20blocked%20here.%5Cn%5Cn---%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/60%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-06-21T10%3A39%3A37Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40dholbach%20still%20working%20on%20%5BSubversion%20support%5D%28https%3A//github.com/ubuntu-core/snapcraft/pull/567%29.%22%2C%20%22created_at%22%3A%20%222016-06-21T10%3A41%3A03Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3689821%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tsimonq2%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40dholbach%20%40didrocks%20Subversion%20support%20%5Bhas%20been%20merged%5D%28https%3A//github.com/ubuntu-core/snapcraft/commit/0e1ec16e6016f08d17f53763b2589ac608fe33e6%29%2C%20so%20can%20this%20be%20merged%20as%20well%3F%22%2C%20%22created_at%22%3A%20%222016-06-23T00%3A52%3A08Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3689821%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tsimonq2%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%27d%20rather%20wait%20until%20it%20lands%20in%20the%20archive.%5Cn%5Cn---%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/60%23-%3A-KKvrLYh4rSxm-zX8Ml2%3A-2055668507%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-06-23T06%3A06%3A07Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40dholbach%202.12%20is%20in%20the%20archive.%20Now%3F%20%22%2C%20%22created_at%22%3A%20%222016-07-04T15%3A31%3A48Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3689821%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tsimonq2%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%2A%5Bsylpheed/snapcraft.yaml%2C%20line%2014%20%5C%5C%5Br2%5C%5C%5D%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/60%23-KLthfN14kL0oIcivwNT%3A-KLthfN14kL0oIcivwNU%3A-151455424%29%20%28%5Braw%20file%5D%28https%3A//github.com/ubuntu/snappy-playpen/blob/95b063a13885d1d26b58ffeec795c16e0ba8bb57/sylpheed/snapcraft.yaml%23L14%29%29%3A%2A%5Cn%3E%20%60%60%60YAML%5Cn%3E%20parts%3A%5Cn%3E%20%20%20%20%20sylpheed%3A%5Cn%3E%20%20%20%20%20%20%20%20%20plugin%3A%20autotools%5Cn%3E%20%60%60%60%5Cn%5CnIt%20seems%20to%20fail%20to%20build%3A%20https%3A//travis-ci.org/ubuntu/snappy-playpen/builds/137763576%20-%20%60autogen.sh%60%20can%27t%20run%20%60aclocal-1.14%60%20because%20it%27s%20not%20available.%5Cn%5Cn---%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/60%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-07-05T06%3A20%3A15Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%2C%20%7B%22body%22%3A%20%22It%20looks%20like%20it%20still%20fails%20to%20build.%20%3A-/%5Cn%5Cn---%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/60%23-%3A-KLthkgIWyNNbKZ4anW2%3A-841838090%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-07-05T06%3A20%3A41Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/ubuntu/snappy-playpen/pull/60#issuecomment-225932282'>General Comment</a></b>
- <a href='https://github.com/tsimonq2'></a> E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_4.4.0-22.40_amd64.deb  404  Not Found [IP: 91.189.88.152 80] - I feel like this isn't something I control...
- <a href='https://github.com/dplanella'></a> Thanks Simon for the pull request! Instead of adding a new copy of the wrapper, would you mind using the `gtkconf` wiki part as [Leafpad](https://github.com/ubuntu/snappy-playpen/blob/master/leafpad/snapcraft.yaml) and [Ristretto](https://github.com/ubuntu/snappy-playpen/blob/master/ristretto/snapcraft.yaml#L39) do?
  Essentially, it's about:
- Removing the custom wrapper
- Modifying snapcraft.yaml to:
- Set the command to be `gtk-launch sylpheed`
- Add the `gtkconf` wiki part
- Add either `libgtk2.0-bin` or `libgtk-3-0-bin` to `stage-packages`
- <a href='https://github.com/tsimonq2'></a> @dplanella Will do, thanks for the feedback!
- <a href='https://github.com/dholbach'></a> _[sylpheed/snapcraft.yaml, line 15 [r2]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/60#-KKmXkuMTXmPCq5khNFI:-KKmXkuNIYof7Nw6nqgx:1185909849) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/95b063a13885d1d26b58ffeec795c16e0ba8bb57/sylpheed/snapcraft.yaml#L15)):_
  > `YAML
  >     sylpheed:
  >         plugin: autotools
  >         source: svn://sylpheed.sraoss.jp/sylpheed/trunk
  >`
  We are still blocked here.
  ---
  _Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/60)_
  
- <a href='https://github.com/tsimonq2'></a> @dholbach still working on [Subversion support](https://github.com/ubuntu-core/snapcraft/pull/567).
- <a href='https://github.com/tsimonq2'></a> @dholbach @didrocks Subversion support [has been merged](https://github.com/ubuntu-core/snapcraft/commit/0e1ec16e6016f08d17f53763b2589ac608fe33e6), so can this be merged as well?
## \- <a href='https://github.com/dholbach'></a> I'd rather wait until it lands in the archive.

_Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/60#-:-KKvrLYh4rSxm-zX8Ml2:-2055668507)_

- <a href='https://github.com/tsimonq2'></a> @dholbach 2.12 is in the archive. Now?
- <a href='https://github.com/dholbach'></a> _[sylpheed/snapcraft.yaml, line 14 [r2]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/60#-KLthfN14kL0oIcivwNT:-KLthfN14kL0oIcivwNU:-151455424) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/95b063a13885d1d26b58ffeec795c16e0ba8bb57/sylpheed/snapcraft.yaml#L14)):_
  > `YAML
  > parts:
  >     sylpheed:
  >         plugin: autotools
  >`
  It seems to fail to build: https://travis-ci.org/ubuntu/snappy-playpen/builds/137763576 - `autogen.sh` can't run `aclocal-1.14` because it's not available.
  ---
  _Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/60)_
  
## \- <a href='https://github.com/dholbach'></a> It looks like it still fails to build. :-/

_Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/60#-:-KLthkgIWyNNbKZ4anW2:-841838090)_

<a href='https://www.codereviewhub.com/ubuntu/snappy-playpen/pull/60?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/ubuntu/snappy-playpen/pull/60?approve=1'></a>&nbsp;<a href='https://github.com/ubuntu/snappy-playpen/pull/60'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by tsimonq2** [comment]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_4.4.0-22.40_amd64.deb  404  Not Found [IP: 91.189.88.152 80] - I feel like this isn't something I control...

**Comment by dplanella** [comment]
Thanks Simon for the pull request! Instead of adding a new copy of the wrapper, would you mind using the `gtk-launch` wiki part as [Leafpad](https://github.com/ubuntu/snappy-playpen/blob/master/leafpad/snapcraft.yaml) and [Ristretto](https://github.com/ubuntu/snappy-playpen/blob/master/ristretto/snapcraft.yaml#L39) do?

Essentially, it's about:
- Removing the custom wrapper
- Modifying snapcraft.yaml to:
  - Set the command to be `gtk-launch sylpheed`
  - Add the `gtkconf` wiki part
  - Add either `libgtk2.0-bin` or `libgtk-3-0-bin` to `stage-packages`

**Comment by tsimonq2** [comment]
@dplanella Will do, thanks for the feedback!

**Comment by dholbach** [comment]
*[sylpheed/snapcraft.yaml, line 15 \[r2\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/60#-KKmXkuMTXmPCq5khNFI:-KKmXkuNIYof7Nw6nqgx:1185909849) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/95b063a13885d1d26b58ffeec795c16e0ba8bb57/sylpheed/snapcraft.yaml#L15)):*
> ```YAML
>     sylpheed:
>         plugin: autotools
>         source: svn://sylpheed.sraoss.jp/sylpheed/trunk
> ```

We are still blocked here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/60)*

**Comment by tsimonq2** [comment]
@dholbach still working on [Subversion support](https://github.com/ubuntu-core/snapcraft/pull/567).

**Comment by tsimonq2** [comment]
@dholbach @didrocks Subversion support [has been merged](https://github.com/ubuntu-core/snapcraft/commit/0e1ec16e6016f08d17f53763b2589ac608fe33e6), so can this be merged as well?

**Comment by dholbach** [comment]
I'd rather wait until it lands in the archive.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/60#-:-KKvrLYh4rSxm-zX8Ml2:-2055668507)*

**Comment by tsimonq2** [comment]
@dholbach 2.12 is in the archive. Now?

**Comment by dholbach** [comment]
*[sylpheed/snapcraft.yaml, line 14 \[r2\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/60#-KLthfN14kL0oIcivwNT:-KLthfN14kL0oIcivwNU:-151455424) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/95b063a13885d1d26b58ffeec795c16e0ba8bb57/sylpheed/snapcraft.yaml#L14)):*
> ```YAML
> parts:
>     sylpheed:
>         plugin: autotools
> ```

It seems to fail to build: https://travis-ci.org/ubuntu/snappy-playpen/builds/137763576 - `autogen.sh` can't run `aclocal-1.14` because it's not available.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/60)*

**Comment by dholbach** [comment]
It looks like it still fails to build. :-/

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/60#-:-KLthkgIWyNNbKZ4anW2:-841838090)*

**Pull request closed without merging**
