### PR TITLE
bring clock snap up to what's proposed for upstreaming: https://code.…

### PR DESCRIPTION
**Pull request by dholbach**
…launchpad.net/~dholbach/ubuntu-clock-app/snap-the-clock/+merge/299947

---
This change is [Reviewable](https://reviewable.io/reviews/ubuntu/snappy-playpen/172)

### CODE REVIEW

**Comment by dplanella** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ubuntu-clock-app/snapcraft.yaml, line 2 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/172#-KMcwE9CcAyxsygVBMI7:-KMcwE9CcAyxsygVBMI8:915656716) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/c404c73fccf59e9f5084c1656d70422076c6279d/ubuntu-clock-app/snapcraft.yaml#L2)):*
> ```YAML
> name: ubuntu-clock-app
> version: 3.6+snap2
> ```

It might be worth checking if in the meantime the upstream version has changed and needs bumping. If we're to upload this to the store, then it might be worth bumping the `snap2` part. Finally, I've seen people enclosing versions in quotes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/172)*

**Comment by dplanella** [comment]
While we're at it, I'd suggest adding a README.md file for clock, explaining why we're not using the desktop launcher. I.e. it needs this variable for Clock to find it's custom QML plugins, which we cannot pass through the launcher:

`export QML2_IMPORT_PATH=$SNAP/usr/lib/$ARCH/qt5/qml/ClockApp`

**Comment by dholbach** [comment]
*[ubuntu-clock-app/snapcraft.yaml, line 2 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/172#-KMcwE9CcAyxsygVBMI7:-KMdNSkFW5m6_FlpsmpQ:-499146009) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/c404c73fccf59e9f5084c1656d70422076c6279d/ubuntu-clock-app/snapcraft.yaml#L2)):*
<details><summary><i>Previously, dplanella (David Planella) wrote…</i></summary>
> It might be worth checking if in the meantime the upstream version has changed and needs bumping. If we're to upload this to the store, then it might be worth bumping the `snap2` part. Finally, I've seen people enclosing versions in quotes.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/172)*

**Comment by dplanella** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ubuntu-clock-app/README.md, line 14 \[r2\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/172#-KMdPbMtceYDOJl7XoCj:-KMdPbMuJHsDtRVtdPy2:-344181318) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/10dafdcec356f2dd9c8586342c53d86404291bd2/ubuntu-clock-app/README.md#L14)):*
> ```Markdown
> 
> Working features:
>  - all
> ```

Unfortunately not. We should probably add:
- Preferences not saved
- Alarms not saved
- Added timezones not saved.

Some of the errors that come up: http://pastebin.ubuntu.com/19358436/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/172)*

**Comment by dholbach** [comment]
*[ubuntu-clock-app/README.md, line 14 \[r2\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/172#-KMdPbMtceYDOJl7XoCj:-KMdR70eqpToXVTc1sXJ:-1694677584) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/10dafdcec356f2dd9c8586342c53d86404291bd2/ubuntu-clock-app/README.md#L14)):*
<details><summary><i>Previously, dplanella (David Planella) wrote…</i></summary>
> Unfortunately not. We should probably add:
> - Preferences not saved
> - Alarms not saved
> - Added timezones not saved.
> 
> Some of the errors that come up: http://pastebin.ubuntu.com/19358436/
</details>
I'm doing another test now. Thanks a lot for the feedback - you know the app clearly much better than I do. ;-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/172)*

**Comment by dholbach** [comment]
*[ubuntu-clock-app/README.md, line 14 \[r2\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/172#-KMdPbMtceYDOJl7XoCj:-KMdRqiIa25mRGrv_KRU:-499146009) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/10dafdcec356f2dd9c8586342c53d86404291bd2/ubuntu-clock-app/README.md#L14)):*
<details><summary><i>Previously, dholbach (Daniel Holbach) wrote…</i></summary>
> I'm doing another test now. Thanks a lot for the feedback - you know the app clearly much better than I do. ;-)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/172)*

**Comment by dplanella** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ubuntu-clock-app/snapcraft.yaml, line 10 \[r3\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/172#-KMdTPKS0m3Ol5ohXSyQ:-KMdTPKTgraXEtnsvt5F:-55026146) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/76ec9e4d122b13a48c62a03e14020a03951a233c/ubuntu-clock-app/snapcraft.yaml#L10)):*
> ```YAML
>   ubuntu-clock-app:
>     command: clock
>     plugs: [unity7, opengl, network, network-bind]
> ```

Did these help with the network errors? Sorry, on my last comment I hadn't realized that not even `network` was declared. Perhaps `network-bind` is not even needed.  A way to test if network access works is to go to "Add city" and look for an obscure city that's not in the most frequently used list. Clock will then search on the Internet and will return an error if it can access the networl

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/172)*

**Comment by dholbach** [comment]
*[ubuntu-clock-app/snapcraft.yaml, line 10 \[r3\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/172#-KMdTPKS0m3Ol5ohXSyQ:-KMdVVe1egGCxRL9mLSX:-257912381) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/76ec9e4d122b13a48c62a03e14020a03951a233c/ubuntu-clock-app/snapcraft.yaml#L10)):*
<details><summary><i>Previously, dplanella (David Planella) wrote…</i></summary>
> Did these help with the network errors? Sorry, on my last comment I hadn't realized that not even `network` was declared. Perhaps `network-bind` is not even needed.  A way to test if network access works is to go to "Add city" and look for an obscure city that's not in the most frequently used list. Clock will then search on the Internet and will return an error if it can access the networl
</details>
It looks like both are required, with just `network` the app will hang. Maybe I misremember, but I seem to recall that this is a bug because hostname lookups currently still require `..-bind`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/172)*

**Pull request merged**
