### PR TITLE
Read styleguide compliance to ImageMagick

### PR DESCRIPTION
**Pull request by didrocks**
This change is [Reviewable](https://reviewable.io/reviews/ubuntu/snappy-playpen/95)

### CODE REVIEW

**Comment by didrocks** [comment]
I hope you will love those changes!

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/95#-:-KKmGDpKPf_iDYtIEK8p:-310202982)*

**Comment by dholbach** [comment]
*[imagemagick-edge/snapcraft.yaml, line 57 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/95#-KKmH4Xnavh608ZeM_L0:-KKmH4XoUo2eHjsXMWxm:1983719297) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/7d170e2a487c65b2c60f39fb713f9daf126caed9/imagemagick-edge/snapcraft.yaml#L57)):*
> ```YAML
> parts:
>   imagemagick:
>     source: git://github.com/ImageMagick/ImageMagick.git
> ```

This needs fixing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/95)*

**Comment by didrocks** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[imagemagick-edge/snapcraft.yaml, line 57 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/95#-KKmH4Xnavh608ZeM_L0:-KKmHWT7Mq0yPtns6StD:-365487795) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/7d170e2a487c65b2c60f39fb713f9daf126caed9/imagemagick-edge/snapcraft.yaml#L57)):*
<details><summary><i>Previously, dholbach (Daniel Holbach) wrote…</i></summary>
> This needs fixing.
</details>
Good catch, fixing now!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/95)*

**Comment by dholbach** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/95#-:-KKmInDvGNQLSQlDIl5p:1417088721)*

**Comment by dholbach** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/95)*

**Pull request merged**
