### PR TITLE
added the snap name for qownnotes

### PR DESCRIPTION
**Pull request by pbek**
This change is [Reviewable](https://reviewable.io/reviews/ubuntu/snappy-playpen/164)

### CODE REVIEW

**Comment by dholbach** [comment]
*[README.md, line 42 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/164#-KMUb8IkkGH_UG_AP6tc:-KMUb8IkkGH_UG_AP6td:1461014444) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/5e19a974d5ac61aed204c5420ba8b972b415d762/README.md#L42)):*
> ```Markdown
> | :white_check_mark:  | `qcomicbook`       |                           | cmake, qt5                |
> | :red_circle:        | `qdriverstation`   |                           | frc, qmake, qt5, robotics |
> | :white_check_mark:  | `qownnotes`        | [qownnotes][qownnotes]    | qmake, qt5, tar           |
> ```

This is actually for linking to the app in the store. There's no link mentioned below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/164)*

**Comment by pbek** [comment]
I'm sorry, I first thought that might be generated automatically, but how should that work here on github. :)

**Comment by dholbach** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/164#-:-KMYpgprbw5vs2yweO4L:1417088721)*

**Comment by dholbach** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/164)*

**Pull request merged**
