### PR TITLE
Initial version of ps_mem snap (called ps-mem here)

### PR DESCRIPTION
**Pull request by popey**
Created a snap as requested by @mhall119 - note that the snap is called ps-mem rather than upstream ps_mem because snapcraft barfs if you have a section with an underscore.

 ¯\_(ツ)_/¯

---
This change is [Reviewable](https://reviewable.io/reviews/ubuntu/snappy-playpen/185)

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/ubuntu/snappy-playpen/pull/185%23issuecomment-233862885%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/185%23issuecomment-233864817%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/185%23issuecomment-233864881%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/185%23issuecomment-233866685%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/185%23issuecomment-233866803%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/185%23issuecomment-233867767%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/185%23issuecomment-233869788%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/185%23issuecomment-233869923%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/185%23issuecomment-233886162%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/185%23issuecomment-233889643%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/185%23issuecomment-233905182%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/185%23issuecomment-233862885%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Is%20the%20underscore%20something%20that%20should%20be%20raised%20with%20the%20snap%20people%3F%5Cn%5Cn---%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/185%23-%3A-KN69YvGowkte6IhtF7M%3A-75956200%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-07-20T07%3A17%3A22Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%2C%20%7B%22body%22%3A%20%22Can%20you%20update%20the%20top-level%20README.md%20too%3F%5Cn%5Cn---%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/185%23-%3A-KN6C8D04yt7HRKMlL-S%3A-1461492136%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-07-20T07%3A28%3A36Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%2A%5Bps-mem/snapcraft.yaml%2C%20line%205%20%5C%5C%5Br1%5C%5C%5D%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/185%23-KN6CF-7JhzuF7H60LQ2%3A-KN6CF-7JhzuF7H60LQ3%3A542553498%29%20%28%5Braw%20file%5D%28https%3A//github.com/ubuntu/snappy-playpen/blob/07ace6dbf46d4e78686e998522e9ef7f1c47636f/ps-mem/snapcraft.yaml%23L5%29%29%3A%2A%5Cn%3E%20%60%60%60YAML%5Cn%3E%20summary%3A%20A%20utility%20to%20accurately%20report%20the%20core%20memory%20usage%20for%20a%20program%5Cn%3E%20description%3A%20%7C%5Cn%3E%20%60%60%60%5Cn%5CnThis%20is%20empty.%5Cn%5Cn---%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/185%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-07-20T07%3A28%3A55Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%5Cn%5Cn%5CnReview%20status%3A%200%20of%202%20files%20reviewed%20at%20latest%20revision%2C%201%20unresolved%20discussion.%5Cn%5Cn---%5Cn%5Cn%2A%5Bps-mem/snapcraft.yaml%2C%20line%205%20%5C%5C%5Br1%5C%5C%5D%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/185%23-KN6CF-7JhzuF7H60LQ2%3A-KN6DwIzZlcEkXRP_uqj%3A-1641635717%29%20%28%5Braw%20file%5D%28https%3A//github.com/ubuntu/snappy-playpen/blob/07ace6dbf46d4e78686e998522e9ef7f1c47636f/ps-mem/snapcraft.yaml%23L5%29%29%3A%2A%5Cn%3Cdetails%3E%3Csummary%3E%3Ci%3EPreviously%2C%20dholbach%20%28Daniel%20Holbach%29%20wrote%5Cu2026%3C/i%3E%3C/summary%3E%5Cn%3E%20This%20is%20empty.%5Cn%3C/details%3E%5CnThis%20is%20intentional.%20I%20am%20not%20allowed%20to%20not%20specify%20a%20description%20%28which%20is%20mental%29%20and%20so%20I%20have%20to%20leave%20one%20blank.%5Cn%5Cn---%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/185%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-07-20T07%3A37%3A11Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1841272%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/popey%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%5Cn%5Cn%5CnReview%20status%3A%200%20of%202%20files%20reviewed%20at%20latest%20revision%2C%202%20unresolved%20discussions.%5Cn%5Cn---%5Cn%5Cn%2A%5Bps-mem/snapcraft.yaml%2C%20line%2014%20%5C%5C%5Br1%5C%5C%5D%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/185%23-KN6EEEwFwmycTax_2Lu%3A-KN6EEEwFwmycTax_2Lv%3A-669036166%29%20%28%5Braw%20file%5D%28https%3A//github.com/ubuntu/snappy-playpen/blob/07ace6dbf46d4e78686e998522e9ef7f1c47636f/ps-mem/snapcraft.yaml%23L14%29%29%3A%2A%5Cn%3E%20%60%60%60YAML%5Cn%3E%20parts%3A%5Cn%3E%20%20%20ps-mem%3A%5Cn%3E%20%20%20%20%20plugin%3A%20python3%5Cn%3E%20%60%60%60%5Cn%5CnCan%20you%20put%20plugin%20after%20source%20please%3F%5Cn%5Cn---%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/185%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-07-20T07%3A37%3A47Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1823296%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/didrocks%22%7D%7D%2C%20%7B%22body%22%3A%20%22It%27s%20not%20allowed%20to%20use%20underscore%2C%20and%20we%20can%27t%20change%20that%2C%20so%20the%20answer%20from%20snapcraft%20people%20is%20%5C%22change%20the%20underscore%20to%20a%20hyphen%5C%22.%5Cn%5Cn---%5Cn%5CnReview%20status%3A%200%20of%202%20files%20reviewed%20at%20latest%20revision%2C%202%20unresolved%20discussions.%5Cn%5Cn---%5Cn%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/185%23-%3A-KN6ExeZZrzqvz99q5Z3%3A1601648701%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-07-20T07%3A41%3A21Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1841272%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/popey%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%5Cn%5Cn%5CnReviewed%202%20of%202%20files%20at%20r1%2C%202%20of%202%20files%20at%20r2.%5CnReview%20status%3A%20all%20files%20reviewed%20at%20latest%20revision%2C%201%20unresolved%20discussion.%5Cn%5Cn---%5Cn%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/185%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-07-20T07%3A46%3A30Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1823296%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/didrocks%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Cimg%20class%3D%5C%22emoji%5C%22%20title%3D%5C%22%3Algtm%3A%5C%22%20alt%3D%5C%22%3Algtm%3A%5C%22%20align%3D%5C%22absmiddle%5C%22%20src%3D%5C%22https%3A//reviewable.io/lgtm.png%5C%22%20height%3D%5C%2220%5C%22%20width%3D%5C%2261%5C%22/%3E%5Cn%5Cn---%5Cn%5CnReview%20status%3A%20all%20files%20reviewed%20at%20latest%20revision%2C%201%20unresolved%20discussion.%5Cn%5Cn---%5Cn%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/185%23-%3A-KN6GJyCicBvPtkX1441%3A1417088721%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-07-20T07%3A46%3A41Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1823296%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/didrocks%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%2A%5Bps-mem/snapcraft.yaml%2C%20line%205%20%5C%5C%5Br1%5C%5C%5D%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/185%23-KN6CF-7JhzuF7H60LQ2%3A-KN6RXt9Ihy5WZ9XLKK8%3A-804092494%29%20%28%5Braw%20file%5D%28https%3A//github.com/ubuntu/snappy-playpen/blob/07ace6dbf46d4e78686e998522e9ef7f1c47636f/ps-mem/snapcraft.yaml%23L5%29%29%3A%2A%5Cn%3Cdetails%3E%3Csummary%3E%3Ci%3EPreviously%2C%20popey%20%28Alan%20Pope%29%20wrote%5Cu2026%3C/i%3E%3C/summary%3E%5Cn%3E%20This%20is%20intentional.%20I%20am%20not%20allowed%20to%20not%20specify%20a%20description%20%28which%20is%20mental%29%20and%20so%20I%20have%20to%20leave%20one%20blank.%5Cn%3C/details%3E%5CnWhy%20is%20this%20mental%3F%20Doesn%27t%20it%20make%20sense%20to%20explain%20to%20users%20what%20the%20snap%20is%20for%3F%5Cn%5Cn---%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/185%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-07-20T08%3A36%3A13Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%5Cn%5Cn%5CnReview%20status%3A%20all%20files%20reviewed%20at%20latest%20revision%2C%201%20unresolved%20discussion.%5Cn%5Cn---%5Cn%5Cn%2A%5Bps-mem/snapcraft.yaml%2C%20line%205%20%5C%5C%5Br1%5C%5C%5D%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/185%23-KN6CF-7JhzuF7H60LQ2%3A-KN6U-REyxF-x6LMzvCN%3A1426226005%29%20%28%5Braw%20file%5D%28https%3A//github.com/ubuntu/snappy-playpen/blob/07ace6dbf46d4e78686e998522e9ef7f1c47636f/ps-mem/snapcraft.yaml%23L5%29%29%3A%2A%5Cn%3Cdetails%3E%3Csummary%3E%3Ci%3EPreviously%2C%20dholbach%20%28Daniel%20Holbach%29%20wrote%5Cu2026%3C/i%3E%3C/summary%3E%5Cn%3E%20Why%20is%20this%20mental%3F%20Doesn%27t%20it%20make%20sense%20to%20explain%20to%20users%20what%20the%20snap%20is%20for%3F%5Cn%3C/details%3E%5CnThe%20summary%20fully%20describes%20the%20project.%20I%20could%20make%20up%20some%20rubbish%20to%20go%20there%2C%20but%20I%20don%27t%20think%20we%20should%20have%20to%20enforce%20that.%20Some%20things%20are%20just%20tiny%20and%20one%20line%20describes%20it%20well.%5Cn%5Cn---%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/185%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-07-20T08%3A47%3A06Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1841272%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/popey%22%7D%7D%2C%20%7B%22body%22%3A%20%22Ok...%20wfm.%22%2C%20%22created_at%22%3A%20%222016-07-20T09%3A55%3A19Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/ubuntu/snappy-playpen/pull/185#issuecomment-233862885'>General Comment</a></b>
- <a href='https://github.com/dholbach'></a> Is the underscore something that should be raised with the snap people?
---
*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185#-:-KN69YvGowkte6IhtF7M:-75956200)*

- <a href='https://github.com/dholbach'></a> Can you update the top-level README.md too?
---
*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185#-:-KN6C8D04yt7HRKMlL-S:-1461492136)*

- <a href='https://github.com/dholbach'></a> *[ps-mem/snapcraft.yaml, line 5 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185#-KN6CF-7JhzuF7H60LQ2:-KN6CF-7JhzuF7H60LQ3:542553498) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/07ace6dbf46d4e78686e998522e9ef7f1c47636f/ps-mem/snapcraft.yaml#L5)):*
> ```YAML
> summary: A utility to accurately report the core memory usage for a program
> description: |
> ```
This is empty.
---
*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185)*

- <a href='https://github.com/popey'></a> Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.
---
*[ps-mem/snapcraft.yaml, line 5 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185#-KN6CF-7JhzuF7H60LQ2:-KN6DwIzZlcEkXRP_uqj:-1641635717) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/07ace6dbf46d4e78686e998522e9ef7f1c47636f/ps-mem/snapcraft.yaml#L5)):*
<details><summary><i>Previously, dholbach (Daniel Holbach) wrote…</i></summary>
> This is empty.
</details>
This is intentional. I am not allowed to not specify a description (which is mental) and so I have to leave one blank.
---
*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185)*

- <a href='https://github.com/didrocks'></a> Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.
---
*[ps-mem/snapcraft.yaml, line 14 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185#-KN6EEEwFwmycTax_2Lu:-KN6EEEwFwmycTax_2Lv:-669036166) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/07ace6dbf46d4e78686e998522e9ef7f1c47636f/ps-mem/snapcraft.yaml#L14)):*
> ```YAML
> parts:
>   ps-mem:
>     plugin: python3
> ```
Can you put plugin after source please?
---
*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185)*

- <a href='https://github.com/popey'></a> It's not allowed to use underscore, and we can't change that, so the answer from snapcraft people is "change the underscore to a hyphen".
---
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.
---
*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185#-:-KN6ExeZZrzqvz99q5Z3:1601648701)*

- <a href='https://github.com/didrocks'></a> Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.
---
*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185)*

- <a href='https://github.com/didrocks'></a> :lgtm:
---
Review status: all files reviewed at latest revision, 1 unresolved discussion.
---
*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185#-:-KN6GJyCicBvPtkX1441:1417088721)*

- <a href='https://github.com/dholbach'></a> *[ps-mem/snapcraft.yaml, line 5 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185#-KN6CF-7JhzuF7H60LQ2:-KN6RXt9Ihy5WZ9XLKK8:-804092494) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/07ace6dbf46d4e78686e998522e9ef7f1c47636f/ps-mem/snapcraft.yaml#L5)):*
<details><summary><i>Previously, popey (Alan Pope) wrote…</i></summary>
> This is intentional. I am not allowed to not specify a description (which is mental) and so I have to leave one blank.
</details>
Why is this mental? Doesn't it make sense to explain to users what the snap is for?
---
*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185)*

- <a href='https://github.com/popey'></a> Review status: all files reviewed at latest revision, 1 unresolved discussion.
---
*[ps-mem/snapcraft.yaml, line 5 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185#-KN6CF-7JhzuF7H60LQ2:-KN6U-REyxF-x6LMzvCN:1426226005) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/07ace6dbf46d4e78686e998522e9ef7f1c47636f/ps-mem/snapcraft.yaml#L5)):*
<details><summary><i>Previously, dholbach (Daniel Holbach) wrote…</i></summary>
> Why is this mental? Doesn't it make sense to explain to users what the snap is for?
</details>
The summary fully describes the project. I could make up some rubbish to go there, but I don't think we should have to enforce that. Some things are just tiny and one line describes it well.
---
*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185)*

- <a href='https://github.com/dholbach'></a> Ok... wfm.

<a href='https://www.codereviewhub.com/ubuntu/snappy-playpen/pull/185?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/ubuntu/snappy-playpen/pull/185?approve=1'></a>&nbsp;<a href='https://github.com/ubuntu/snappy-playpen/pull/185'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dholbach** [comment]
Is the underscore something that should be raised with the snap people?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185#-:-KN69YvGowkte6IhtF7M:-75956200)*

**Comment by dholbach** [comment]
Can you update the top-level README.md too?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185#-:-KN6C8D04yt7HRKMlL-S:-1461492136)*

**Comment by dholbach** [comment]
*[ps-mem/snapcraft.yaml, line 5 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185#-KN6CF-7JhzuF7H60LQ2:-KN6CF-7JhzuF7H60LQ3:542553498) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/07ace6dbf46d4e78686e998522e9ef7f1c47636f/ps-mem/snapcraft.yaml#L5)):*
> ```YAML
> summary: A utility to accurately report the core memory usage for a program
> description: |
> ```

This is empty.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185)*

**Comment by popey** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[ps-mem/snapcraft.yaml, line 5 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185#-KN6CF-7JhzuF7H60LQ2:-KN6DwIzZlcEkXRP_uqj:-1641635717) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/07ace6dbf46d4e78686e998522e9ef7f1c47636f/ps-mem/snapcraft.yaml#L5)):*
<details><summary><i>Previously, dholbach (Daniel Holbach) wrote…</i></summary>
> This is empty.
</details>
This is intentional. I am not allowed to not specify a description (which is mental) and so I have to leave one blank.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185)*

**Comment by didrocks** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[ps-mem/snapcraft.yaml, line 14 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185#-KN6EEEwFwmycTax_2Lu:-KN6EEEwFwmycTax_2Lv:-669036166) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/07ace6dbf46d4e78686e998522e9ef7f1c47636f/ps-mem/snapcraft.yaml#L14)):*
> ```YAML
> parts:
>   ps-mem:
>     plugin: python3
> ```

Can you put plugin after source please?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185)*

**Comment by popey** [comment]
It's not allowed to use underscore, and we can't change that, so the answer from snapcraft people is "change the underscore to a hyphen".

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185#-:-KN6ExeZZrzqvz99q5Z3:1601648701)*

**Comment by didrocks** [comment]
Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185)*

**Comment by didrocks** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185#-:-KN6GJyCicBvPtkX1441:1417088721)*

**Comment by dholbach** [comment]
*[ps-mem/snapcraft.yaml, line 5 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185#-KN6CF-7JhzuF7H60LQ2:-KN6RXt9Ihy5WZ9XLKK8:-804092494) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/07ace6dbf46d4e78686e998522e9ef7f1c47636f/ps-mem/snapcraft.yaml#L5)):*
<details><summary><i>Previously, popey (Alan Pope) wrote…</i></summary>
> This is intentional. I am not allowed to not specify a description (which is mental) and so I have to leave one blank.
</details>
Why is this mental? Doesn't it make sense to explain to users what the snap is for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185)*

**Comment by popey** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ps-mem/snapcraft.yaml, line 5 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185#-KN6CF-7JhzuF7H60LQ2:-KN6U-REyxF-x6LMzvCN:1426226005) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/07ace6dbf46d4e78686e998522e9ef7f1c47636f/ps-mem/snapcraft.yaml#L5)):*
<details><summary><i>Previously, dholbach (Daniel Holbach) wrote…</i></summary>
> Why is this mental? Doesn't it make sense to explain to users what the snap is for?
</details>
The summary fully describes the project. I could make up some rubbish to go there, but I don't think we should have to enforce that. Some things are just tiny and one line describes it well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/185)*

**Comment by dholbach** [comment]
Ok... wfm.

**Pull request merged**
