### PR TITLE
re-add MIT license

### PR DESCRIPTION
**Pull request by dholbach**
Sorry for the noise everyone.

We wanted to get everybody's go-ahead in https://github.com/ubuntu/snappy-playpen/pull/28 first, but the merge button was pressed a bit too quickly.

We have the +1 from @didrocks @popey @dholbach and @caldav 

Still waiting for a reply from @Winael @dplanella @rednoah @elopio @cwayne18 @nskaggs

### CODE REVIEW

**Comment by dplanella** [comment]
+1

**Comment by cwayne18** [comment]
+1

**Comment by nskaggs** [comment]
+1

**Comment by elopio** [comment]
+1

**Comment by dholbach** [comment]
Now it's just @Winael and @rednoah - can you maybe comment as well?

**Comment by rednoah** [comment]
+1 works for me, i don't care

**Comment by Winael** [comment]
+1 too

**Pull request merged**
