### PR TITLE
Add working OpenTTD project

### PR DESCRIPTION
**Pull request by popey**
Tested both on my laptop and on a clean Ubuntu VM.

---
This change is [Reviewable](https://reviewable.io/reviews/ubuntu/snappy-playpen/133)

### CODE REVIEW

**Comment by didrocks** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[openttd/snapcraft.yaml, line 14 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/133#-KLq1YuHQWSkpDIHgaMG:-KLq1YuHQWSkpDIHgaMH:1511525626) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/e71f66251fa6fa74e2a1adab6576c1c17a7db5ae/openttd/snapcraft.yaml#L14)):*
> ```YAML
>   this up).
> 
> confinement: devmode  # use "strict" to enforce system access only via declared interfaces
> ```

I saw you added some plugs, does it work with them (and so, no devmode?)

---

*[openttd/snapcraft.yaml, line 23 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/133#-KLq1dI6K-A2Rm1Wrc93:-KLq1dI7tiKQxfnYfKUd:246096451) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/e71f66251fa6fa74e2a1adab6576c1c17a7db5ae/openttd/snapcraft.yaml#L23)):*
> ```YAML
> parts:
>   openttd:
>     after: [desktop/qt5]
> ```

Could this be moved as last item as per our best practices?

---

*[openttd/snapcraft.yaml, line 25 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/133#-KLq1jmFCmVC43xrVTEP:-KLq1jmGG3s5wh_42L0Q:726332954) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/e71f66251fa6fa74e2a1adab6576c1c17a7db5ae/openttd/snapcraft.yaml#L25)):*
> ```YAML
>     after: [desktop/qt5]
>     source: http://binaries.openttd.org/releases/1.6.1/openttd-1.6.1-linux-generic-amd64.tar.gz
>     source-type: tar
> ```

I guess this isn't needed (.tar.gz is autodetected as tar)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/133)*

**Comment by popey** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[openttd/snapcraft.yaml, line 14 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/133#-KLq1YuHQWSkpDIHgaMG:-KLqAhIkGl3anN3vtPc3:-549810499) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/e71f66251fa6fa74e2a1adab6576c1c17a7db5ae/openttd/snapcraft.yaml#L14)):*
<details><summary><i>Previously, didrocks (Didier Roche) wrote…</i></summary>
> I saw you added some plugs, does it work with them (and so, no devmode?)
</details>
Not tested in strict mode, only in devmode.

---

*[openttd/snapcraft.yaml, line 25 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/133#-KLq1jmFCmVC43xrVTEP:-KLqAyDRg8kmKQFA6hIf:472308542) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/e71f66251fa6fa74e2a1adab6576c1c17a7db5ae/openttd/snapcraft.yaml#L25)):*
<details><summary><i>Previously, didrocks (Didier Roche) wrote…</i></summary>
> I guess this isn't needed (.tar.gz is autodetected as tar)
</details>
Whilst it's not needed, I like it being there because then grepping for "source-type" is actually useful. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/133)*

**Comment by didrocks** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[openttd/snapcraft.yaml, line 14 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/133#-KLq1YuHQWSkpDIHgaMG:-KLqDcjIfeNKhzaT44Xy:-2111445401) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/e71f66251fa6fa74e2a1adab6576c1c17a7db5ae/openttd/snapcraft.yaml#L14)):*
> Not tested in strict mode, only in devmode.
> 1 MINUTE AGO
> 
>  
>  

Maybe remove the `plugs` stenza then, to not confused people.

---

*[openttd/snapcraft.yaml, line 25 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/133#-KLq1jmFCmVC43xrVTEP:-KLqDkqRFDaLgqaJ0UxA:509284503) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/e71f66251fa6fa74e2a1adab6576c1c17a7db5ae/openttd/snapcraft.yaml#L25)):*
<details><summary><i>Previously, popey (Alan Pope) wrote…</i></summary>
> Whilst it's not needed, I like it being there because then grepping for "source-type" is actually useful. 
</details>
Hum, ok, not really a fan to have verbose for verbose mode (and I don't see in which case grepping for  `source-type` would help). but ok :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/133)*

**Comment by didrocks** [comment]
Thanks for the changes!

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/133#-:-KLtirs8eNmnBMgWtqoD:629839926)*

**Pull request merged**
