### PR TITLE
added a snapcraft for QOwnNotes

### PR DESCRIPTION
**Pull request by pbek**
added a snapcraft for QOwnNotes, the plain-text file notepad with markdown support and ownCloud integration (http://www.qownnotes.org/)

---
This change is [Reviewable](https://reviewable.io/reviews/ubuntu/snappy-playpen/156)

### CODE REVIEW

**Comment by dholbach** [comment]
Nice work, can you add QOwnNotes to the top-level `README.md` of the Snappy Playpen repo too?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/156#-:-KMNw-FMZ2VVCVtNskSH:-676738031)*

**Comment by dholbach** [comment]
*[qownnotes/README.md, line 19 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/156#-KMNwBV-qui33_wwSfYo:-KMNwBV-qui33_wwSfYp:1886052121) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/544f4dd2d3d9b0d90f2dd62b8a3b2256d5ddf2c5/qownnotes/README.md#L19)):*
> ```Markdown
> 
> 
> You can also visit [QOwnNotes on GitHub](https://github.com/pbek/QOwnNotes).
> ```

Are all the features working in the snapped version?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/156)*

**Comment by pbek** [comment]
@dholbach: I now added qownnotes to the readme. And yes, all features are working, but of course the snapped application has no access to a note directory the user's home directory. Is there a way to access the home directory too?

**Comment by dholbach** [comment]
Yes, use the `home`plug.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/156#-:-KMPOe8GkMyrWHYj6PWT:-164404255)*

**Comment by dholbach** [comment]
*[qownnotes/snapcraft.yaml, line 18 \[r2\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/156#-KMPOsKd3D_eqvh_Q2Bt:-KMPOsKd3D_eqvh_Q2Bu:-405129944) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/a9077bd45164a1c8a8df1df38674ab0dea6b7fb0/qownnotes/snapcraft.yaml#L18)):*
> ```YAML
>       - network
>       - network-bind
> ```

Add the `home` plug here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/156)*

**Comment by pbek** [comment]
`home` works perfectly, thanks a lot @dholbach

**Comment by dholbach** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/156#-:-KMPTJbh6FYLRFs3k69L:1417088721)*

**Comment by dholbach** [comment]
Reviewed 4 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/156)*

**Comment by dholbach** [comment]
Do you think it'd make sense to also add the `snapcraft.yaml` file to the QOwnNotes repository?

**Comment by pbek** [comment]
To which repository? I already have it here to create snaps: <https://github.com/pbek/QOwnNotes/tree/develop/build-systems/snap/snapcraft>

**Comment by dholbach** [comment]
Nice work, you're always one step ahead! :-)

**Comment by pbek** [comment]
And I'm waiting until <https://code.launchpad.net/~pbek/+snap/qownnotes> finally works (Launchpad needs to update snapd). And I have a snap published at <https://myapps.developer.ubuntu.com>

**Comment by dholbach** [comment]
Fantastic! :-)

**Comment by pbek** [comment]
Although I don't know if/when I'm supposed to find it at <https://apps.ubuntu.com/cat/search/?q=qownnotes&op=>...

**Comment by dholbach** [comment]
On apps.ubuntu.com you can't find snaps, it's only for the .deb packages contained in Ubuntu itself.

**Pull request merged**
