### PR TITLE
Initial intellij idea commit

### PR DESCRIPTION
**Pull request by LyzardKing**
Initial intellij idea snap
Not working at the moment.
It needs to copy the content of 'parts/idea/build/out/dist.unix.ce' to usr/share/idea (just a name that sounds reasonable)
Then it should work.
This can then be used to build pycharm!

---
This change is [Reviewable](https://reviewable.io/reviews/ubuntu/snappy-playpen/115)

### CODE REVIEW

**Comment by didrocks** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[idea/snapcraft.yaml, line 5 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/115#-KL0TEKbicJZ5ZCF3xGy:-KL0TEKbicJZ5ZCF3xGz:1253490556) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/28a948ab357ae3a81b7230a31daae274530c1b92/idea/snapcraft.yaml#L5)):*
> ```YAML
> summary: IntelliJ Idea Community Edition
> description: This is my-snap's description # a longer description for the snap
> confinement: strict
> ```

I would first start with devmode :)

---

*[idea/snapcraft.yaml, line 16 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/115#-KL0TIPqiYHcVu948nL3:-KL0TIPqiYHcVu948nL4:1327965239) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/28a948ab357ae3a81b7230a31daae274530c1b92/idea/snapcraft.yaml#L16)):*
> ```YAML
>         plugin: ant
>         source: https://github.com/JetBrains/intellij-community.git
>         source-type: git
> ```

This isn't needed as your source url is finishing with .git. Also, please set the source before plugin as per our best practices.

---

*[idea/snapcraft.yaml, line 21 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/115#-KL0TQ_XCEMC39m866kZ:-KL0TQ_XCEMC39m866k_:741944247) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/28a948ab357ae3a81b7230a31daae274530c1b92/idea/snapcraft.yaml#L21)):*
> ```YAML
>     ideacopy:
>         plugin: copy
>         source: .
> ```

Same here, please set source because plugin.

---

*[idea/snapcraft.yaml, line 23 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/115#-KL0SNk5g2atC1iNIjYQ:-KL0SNk6TM8ByyWBAT4X:1741012950) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/28a948ab357ae3a81b7230a31daae274530c1b92/idea/snapcraft.yaml#L23)):*
> ```YAML
>         source: .
>         files:
>             'parts/idea/build/out/dist.unix.ce': 'parts/idea/install/usr/share/idea'
> ```

I see why you need to do that (ant install dosn't work or don't do what's supposed to be shipped?)
So, you need to konw that all parts are ran in parallel, so I guess it's trying to copy before the idea part is built.
If you add as the last line:
`after: [idea]`, then, you can copy `parts/idea/build/out/dist.unix.ce`. I suggest you are using as a destination `usr/share/idea` alone. This will be copied as `parts/ideacopy/install/usr/share/idea`, and then, both parts will be assembled in the stage/ directory (otherwise, you will have counting reference issue and such.

So, that would be the badger. Any chance though that we can get the intellij build shipping that file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/115)*

**Comment by LyzardKing** [comment]
Ok, so...
the intellij ant build file ends up creating a directory (out) with all the builds, for linux, mac, win, ... 
From there we need to take the dist.unix.ce, which is the linux version without the custom jre
If I copy something like:
`'build/out/dist.unix.ce': 'install/usr/share/idea`

I get the following error:
Errno 2] No such file or directory:
'/home/galileo/Documents/Projects/snappy-playpen/idea/parts/ideacopy/build/build/out/dist.unix.ce

It has to copy something from the idea part, not ideacopy. That's what I don't understand.

**Comment by didrocks** [comment]
You should rather try (see my explanations above):
`parts/idea/build/out/dist.unix.ce`: `usr/share/idea`
Ensure you have the `after` keyword defined as above

**Comment by LyzardKing** [comment]
I added the after keyword.
The problem is having access to the other "part":
[Errno 2] No such file or directory:
'/home/galileo/Documents/Projects/snappy-
**playpen/idea/parts/ideacopy/build/parts/idea/build/out/dist.unix.ce'**

Do I need to change the source?

**Comment by dholbach** [comment]
This fails to build for me: http://paste.ubuntu.com/17957095/

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/115#-:-KLFlfWLc_OpF_Q3tv1u:1681389580)*

**Comment by LyzardKing** [comment]
It was working for me the other day ...
I'll have another look at it. It could be something to do with the master
branch having changed something.
It was downloading the latest kotlin when I tried it.

**Comment by LyzardKing** [comment]
@dholbach It runs on a cleanbuild for me

**Comment by dholbach** [comment]
*[idea/README.md, line 17 \[r3\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/115#-KLKv9jW6mW9owEbYJNr:-KLKv9jW6mW9owEbYJNs:-1833574173) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/f1d09ab618b13c0c547ddf7ca1806ae97debc97f/idea/README.md#L17)):*
> ```Markdown
> Known issues:
>   - missing theme
>   - uses gtk-launch, should actually only need a launcher for the fonts
> ```

Does something like http://askubuntu.com/questions/791853/snap-package-for-java-swing-and-awt-application-crashes-when-it-is-executed/791887#791887 make it work?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/115)*

**Comment by LyzardKing** [comment]
@dholbach I added the launcher you linked to. It works perfectly!
It still needs to be installed via --devmode, or you get this error when launching:
```
Invalid Log Path: Log path '/home/galileo/.IdeaIC2016/system/log' is inaccessible.
If you have modified the 'idea.log.path' property please make sure it is correct,
otherwise please re-install the IDE.
```

**Comment by dholbach** [comment]
*[idea/README.md, line 17 \[r4\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/115#-KLPuNjOgcrQFc_toiJO:-KLPuNjPy8NeVGQAIysd:-698616634) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/20ffd026e6e88ffddeec297090a8f05b27cb8920/idea/README.md#L17)):*
> ```Markdown
> Known issues:
>   - missing theme
>   - uses gtk-launch, should actually only need a launcher for the fonts
> ```

Maybe you can drop `gtk-launch` from the `README.md` now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/115)*

**Comment by dholbach** [comment]
*[idea/README.md, line 21 \[r4\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/115#-KLPuUu3MF-tvUhFtI9Z:-KLPuUu3MF-tvUhFtI9_:-698616634) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/20ffd026e6e88ffddeec297090a8f05b27cb8920/idea/README.md#L21)):*
> ```Markdown
> 
> TODO:
>  - replace gtk-launch with launcher
> ```

Maybe you can drop `gtk-launch` from the `README.md` now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/115)*

**Comment by dholbach** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/115#-:-KLRNQ21AZvEmXHDUJuB:1417088721)*

**Comment by dholbach** [comment]
Reviewed 3 of 3 files at r3, 2 of 2 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/115)*

**Comment by didrocks** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[idea/snapcraft.yaml, line 5 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/115#-KL0TEKbicJZ5ZCF3xGy:-KLRQ_GdQIjGa1ZVKlGQ:5173665) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/28a948ab357ae3a81b7230a31daae274530c1b92/idea/snapcraft.yaml#L5)):*
<details><summary><i>Previously, didrocks (Didier Roche) wrote…</i></summary>
> I would first start with devmode :)
</details>
OK

---

*[idea/snapcraft.yaml, line 20 \[r5\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/115#-KLRR4trRaFXBg2Lj65m:-KLRR4trRaFXBg2Lj65n:1774092014) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/631052435ef95df91f65f9f28af391f40302f1c1/idea/snapcraft.yaml#L20)):*
> ```YAML
>     source: https://github.com/JetBrains/intellij-community.git
>     plugin: ant
>     build-packages: [openjdk-8-jdk, openjfx]
> ```

Is this  reallyneeded to build it or just at runtime?

---

*[idea/parts/plugins/x-ant.py, line 50 \[r5\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/115#-KLRRUdrozc1-9bMr0Es:-KLRRUdrozc1-9bMr0Et:1282224954) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/631052435ef95df91f65f9f28af391f40302f1c1/idea/parts/plugins/x-ant.py#L50)):*
> ```Python
>         self.run(['ant'])
>         destdir = os.path.join(self.installdir, 'usr', 'share')
>         idea_tarfile = glob.glob(os.path.join(self.builddir, 'out', 'artifacts', '*.tar.gz'))
> ```

I would rather inherit from the ant plugin and only override the needed part, wdyt?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/115)*

**Comment by LyzardKing** [comment]
@didrocks the packages are needed at build time as well.
It would be better to inherit from the plugin, but I'm not sure how.
Or, it could be even better to have another 'part' copy the tarfile, no?

**Comment by didrocks** [comment]
Reviewed 1 of 2 files at r5, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/115)*

**Pull request merged**
