### PR TITLE
Clock snap running on Unity 7 and Unity 8

### PR DESCRIPTION
**Pull request by dplanella**
This snap should work on both versions of Unity.

clockunity8

Known issues:

- For some reason, the .desktop file is not picked up on Unity 7. I've checked for typos, but I've not seen anything obvious.
- On Unity 8 it needs to be installed with `--devmode` to work. Only in Unity 7 does it work with strict confinement.
- On Unity 8 the icon does not appear on the launcher
- On Unity 8 the icon does not appear in the Apps scope

---
This change is [Reviewable](https://reviewable.io/reviews/ubuntu/snappy-playpen/179)

### CODE REVIEW

**Comment by dplanella** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[ubuntu-clock-app/clock.wrapper, line 66 \[r2\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/179#-KMel6vXQtwaHSzgL9Pk:-KMel6vXQtwaHSzgL9Pl:-767006324) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/b610c6c108f64f75bda5391ec59434143b0672c3/ubuntu-clock-app/clock.wrapper#L66)):*
> ```
> 
> cd $SNAP
> exec $SNAP/usr/bin/qmlscene $SNAP/usr/share/ubuntu-clock-app/ubuntu-clock-app.qml --desktop_file_hint=unity8
> ```

I added this as Unity 8 apps seem to use it, but I'm not sure about its function and if it has any effect on Unity 7

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/179)*

**Comment by dplanella** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[ubuntu-clock-app/snapcraft.yaml, line 6 \[r2\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/179#-KMelOqGp538vD47QgbM:-KMelOqGp538vD47QgbN:-1757241868) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/b610c6c108f64f75bda5391ec59434143b0672c3/ubuntu-clock-app/snapcraft.yaml#L6)):*
> ```YAML
> description: The clock app for all Ubuntu devices
> confinement: devmode
> ```

Changed to devmode, as otherwise it does not work under strict confinement in unity 8. Perhaps a unity8 interface is still missing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/179)*

**Comment by dholbach** [comment]
*[ubuntu-clock-app/clock.wrapper, line 66 \[r2\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/179#-KMel6vXQtwaHSzgL9Pk:-KMiNPUPYPbDLH2tlWEj:916743267) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/b610c6c108f64f75bda5391ec59434143b0672c3/ubuntu-clock-app/clock.wrapper#L66)):*
<details><summary><i>Previously, dplanella (David Planella) wrote…</i></summary>
> I added this as Unity 8 apps seem to use it, but I'm not sure about its function and if it has any effect on Unity 7
</details>
Do you think you can add this as an XXX: to the wrapper or README so other who copy and paste this are aware of this? :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/179)*

**Comment by dholbach** [comment]
*[ubuntu-clock-app/snapcraft.yaml, line 6 \[r2\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/179#-KMelOqGp538vD47QgbM:-KMiNZOJ6Nj32xJkTEmd:1436137381) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/b610c6c108f64f75bda5391ec59434143b0672c3/ubuntu-clock-app/snapcraft.yaml#L6)):*
<details><summary><i>Previously, dplanella (David Planella) wrote…</i></summary>
> Changed to devmode, as otherwise it does not work under strict confinement in unity 8. Perhaps a unity8 interface is still missing?
</details>
Do you recall if there were any log messages?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/179)*

**Comment by dholbach** [comment]
*[ubuntu-clock-app/setup/gui/ubuntu-clock-app.desktop, line 134 \[r2\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/179#-KMiNvTdpiaFOWIxLDVI:-KMiNvTdpiaFOWIxLDVJ:2098664214) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/b610c6c108f64f75bda5391ec59434143b0672c3/ubuntu-clock-app/setup/gui/ubuntu-clock-app.desktop#L134)):*
> ```desktop
> Keywords[zh_CN]=time;alarm;alert;clock;world;stopwatch; 时间;闹铃;闹钟;世界时;秒表;
> Keywords[zh_TW]=time;alarm;alert;clock;world;stopwatch;時鐘;鬧鐘;鬧鈴;世界;碼表;
> Exec=ubuntu-clock-app.clock
> ```

I think this is `ubuntu-clock-app` now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/179)*

**Comment by dplanella** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[ubuntu-clock-app/snapcraft.yaml, line 6 \[r2\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/179#-KMelOqGp538vD47QgbM:-KMiw3Wa0okeq0486dgj:395554076) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/b610c6c108f64f75bda5391ec59434143b0672c3/ubuntu-clock-app/snapcraft.yaml#L6)):*
<details><summary><i>Previously, dholbach (Daniel Holbach) wrote…</i></summary>
> Do you recall if there were any log messages?
</details>
Yes, on Unity 8, with strict confinement and using the unity7 plug it said it could not connect to the Mir server and coredumped. I've been told there was some initial work on a unity8 interface, but it's stalled: https://github.com/snapcore/snapd/pull/1229

---

*[ubuntu-clock-app/setup/gui/ubuntu-clock-app.desktop, line 134 \[r2\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/179#-KMiwNGVVIDTZAAhzDXj:-KMiwNGVVIDTZAAhzDXk:2094530863) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/b610c6c108f64f75bda5391ec59434143b0672c3/ubuntu-clock-app/setup/gui/ubuntu-clock-app.desktop#L134)):*
> ```desktop
> Keywords[zh_CN]=time;alarm;alert;clock;world;stopwatch; 时间;闹铃;闹钟;世界时;秒表;
> Keywords[zh_TW]=time;alarm;alert;clock;world;stopwatch;時鐘;鬧鐘;鬧鈴;世界;碼表;
> Exec=ubuntu-clock-app.clock
> ```

Will fix it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/179)*

**Comment by dplanella** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[ubuntu-clock-app/clock.wrapper, line 66 \[r2\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/179#-KMel6vXQtwaHSzgL9Pk:-KMixGRxRyXtqAnAgmFV:-499146009) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/b610c6c108f64f75bda5391ec59434143b0672c3/ubuntu-clock-app/clock.wrapper#L66)):*
<details><summary><i>Previously, dholbach (Daniel Holbach) wrote…</i></summary>
> Do you think you can add this as an XXX: to the wrapper or README so other who copy and paste this are aware of this? :-)
</details>
Done.

---

*[ubuntu-clock-app/setup/gui/ubuntu-clock-app.desktop, line 134 \[r2\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/179#-KMiwNGVVIDTZAAhzDXj:-KMixKHV4X4NcJRc2AZP:-499146009) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/b610c6c108f64f75bda5391ec59434143b0672c3/ubuntu-clock-app/setup/gui/ubuntu-clock-app.desktop#L134)):*
<details><summary><i>Previously, dplanella (David Planella) wrote…</i></summary>
> Will fix it.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/179)*

**Comment by dplanella** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[ubuntu-clock-app/setup/gui/ubuntu-clock-app.desktop, line 134 \[r2\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/179#-KMiNvTdpiaFOWIxLDVI:-KMixPEOr9QY1eGT_rOY:-499146009) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/b610c6c108f64f75bda5391ec59434143b0672c3/ubuntu-clock-app/setup/gui/ubuntu-clock-app.desktop#L134)):*
<details><summary><i>Previously, dholbach (Daniel Holbach) wrote…</i></summary>
> I think this is `ubuntu-clock-app` now.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/179)*

**Comment by dholbach** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/179#-:-KMj-Ut1jdcF5IPvgPqZ:1417088721)*

**Comment by dholbach** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/179)*

**Pull request merged**
