### PR TITLE
Initial gradio commit

### PR DESCRIPTION
**Pull request by LyzardKing**
As written in the README this is not working at the moment.
The scanlog returns this:

> = AppArmor =
> Time: Sep 27 22:09:20
> Log: apparmor="DENIED" operation="open" profile="snap.gradio.gradio" name="/var/lib/snapd/lib/gl/libGL.so.1.0.0" pid=16716 comm="gradio" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
> File: /var/lib/snapd/lib/gl/libGL.so.1.0.0 (read)
> Suggestion:
> - adjust program to read necessary files from $SNAP, $SNAP_DATA, $SNAP_COMMON, $SNAP_USER_DATA or $SNAP_USER_COMMON
> 
> = AppArmor =
> Time: Sep 27 22:09:20
> Log: apparmor="DENIED" operation="open" profile="snap.gradio.gradio" name="/var/lib/snapd/lib/gl/libEGL.so.1" pid=16716 comm="gradio" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
> File: /var/lib/snapd/lib/gl/libEGL.so.1 (read)
> Suggestion:
> - adjust program to read necessary files from $SNAP, $SNAP_DATA, $SNAP_COMMON, $SNAP_USER_DATA or $SNAP_USER_COMMON

### CODE REVIEW

**Comment by dholbach** [comment]
Is the `opengl` plugin missing?

**Comment by LyzardKing** [comment]
I tried adding that (I might have not pushed to github though).
Snappy.debug now shows no errors, but the ones written in the readme persist

**Comment by dholbach** [comment]
It looks like it makes sense to add `opengl`. What I'm seeing now is
```
Unable to fork a new WebProcess: Failed to execute child process "/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess" (No such file or directory).
Unable to fork a new WebProcess: Failed to execute child process "/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess" (No such file or directory).
Failed to register: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Connection ":1.328" is not allowed to own the service "de.haeckerfelix.gradio" due to AppArmor policy
```

**Comment by dholbach** [comment]
This too:
```
= AppArmor =
Time: Sep 28 08:47:13
Log: apparmor="DENIED" operation="open" profile="snap.gradio.gradio" name="/usr/share/glib-2.0/schemas/" pid=11285 comm="desktop-launch" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
File: /usr/share/glib-2.0/schemas/ (read)
Suggestion:
* adjust program to read necessary files from $SNAP, $SNAP_DATA, $SNAP_COMMON, $SNAP_USER_DATA or $SNAP_USER_COMMON
```

**Comment by dholbach** [comment]
The dbus issue might be waiting for https://github.com/snapcore/snapd/pull/1613

**Comment by dholbach** [comment]
Using `--devmode` I get:
```
** Message: Gradio.vala:154: Starting Gradio version 5_0_0_Beta_1!

(gradio:11598): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
** Message: Gradio.vala:174: Release notes: 0.0.0
** Message: Gradio.vala:176: Current: 5_0_0_Beta_1
Unable to fork a new WebProcess: Failed to execute child process "/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess" (No such file or directory).
Unable to fork a new WebProcess: Failed to execute child process "/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess" (No such file or directory).
** Message: Library.vala:107: Reading library data from: /home/daniel/snap/gradio/x2/.local/share/gradio/library.gradio
** Message: Library.vala:126: No gradio library found. 
** Message: Library.vala:132: Successfully imported library

(gradio:11598): GLib-GObject-CRITICAL **: g_object_set: assertion 'G_IS_OBJECT (object)' failed
** Message: MPRIS.vala:34: Successfully initialized MPRIS session.
** Message: MainWindow.vala:76: Desktop session is: ubuntu

(gradio:11598): GLib-GObject-CRITICAL **: g_object_set: assertion 'G_IS_OBJECT (object)' failed
** Message: StationProvider.vala:82: Requested results from 0 to 20
** Message: StationProvider.vala:82: Requested results from 0 to 20
** Message: StationProvider.vala:82: Requested results from 0 to 20

(gradio:11598): GLib-GObject-CRITICAL **: g_object_set: assertion 'G_IS_OBJECT (object)' failed

** (gradio:11598): ERROR **: Util.vala:98: Error with stylesheet: <broken file>:1:0Failed to import: Error opening file /usr/share/gradio/style/style.css: No such file or directory
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)
```
Is there maybe a hard-coded path (`/usr/share/gradio/style/style.css`) in the source?

**Comment by LyzardKing** [comment]
I found a vala file that defines path constants. I suppose this is the problem
https://github.com/haecker-felix/gradio/blob/master/src/Config.vala

**Comment by dholbach** [comment]
Maybe you can talk to upstream to add a build time option for this or something?

**Comment by LyzardKing** [comment]
Not working yet, but relies on autotools instead of cmake, without the hardcoded paths.

**Comment by LyzardKing** [comment]
@dholbach The build now works.
The part missing now is the snapcraft support for dbus. Any news on that?

**Comment by dholbach** [comment]
All I know of is what's in the PR I referred to above, sorry. :-/

**Pull request closed without merging**
