### PR TITLE
Add the etcd snap, in devmode.

### PR DESCRIPTION
**Pull request by elopio**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/ubuntu/snappy-playpen/pull/223%23issuecomment-242775198%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/223%23issuecomment-244003902%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/223%23issuecomment-244833393%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/223%23issuecomment-245602836%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/223%23issuecomment-242775198%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22This%20can%27t%20be%20upstreamed%20because%20of%20https%3A//bugs.launchpad.net/snapcraft/%2Bbug/1615242%5Cr%5CnThe%20links%20in%20the%20etc%20repository%20cause%20an%20infinite%20loop%20when%20used%20with%20the%20local%20source.%22%2C%20%22created_at%22%3A%20%222016-08-26T15%3A56%3A23Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/617831%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elopio%22%7D%7D%2C%20%7B%22body%22%3A%20%22Nice%20work.%20Do%20you%20think%20you%20can%20mention%20the%20custom%20plugin%20and%20the%20bug%20number%20in%20%60./etc/README.md%60%3F%20That%20way%20we%20can%20keep%20track%20of%20this.%22%2C%20%22created_at%22%3A%20%222016-09-01T07%3A54%3A51Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40dholbach%20done.%22%2C%20%22created_at%22%3A%20%222016-09-06T02%3A06%3A58Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/617831%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elopio%22%7D%7D%2C%20%7B%22body%22%3A%20%22Brilliant%2C%20thanks%21%22%2C%20%22created_at%22%3A%20%222016-09-08T13%3A48%3A11Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/ubuntu/snappy-playpen/pull/223#issuecomment-242775198'>General Comment</a></b>
- <a href='https://github.com/elopio'></a> This can't be upstreamed because of https://bugs.launchpad.net/snapcraft/+bug/1615242
The links in the etc repository cause an infinite loop when used with the local source.
- <a href='https://github.com/dholbach'></a> Nice work. Do you think you can mention the custom plugin and the bug number in `./etc/README.md`? That way we can keep track of this.
- <a href='https://github.com/elopio'></a> @dholbach done.
- <a href='https://github.com/dholbach'></a> Brilliant, thanks!

<a href='https://www.codereviewhub.com/ubuntu/snappy-playpen/pull/223?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/ubuntu/snappy-playpen/pull/223?approve=1'></a>&nbsp;<a href='https://github.com/ubuntu/snappy-playpen/pull/223'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by elopio** [comment]
This can't be upstreamed because of https://bugs.launchpad.net/snapcraft/+bug/1615242
The links in the etc repository cause an infinite loop when used with the local source.

**Comment by dholbach** [comment]
Nice work. Do you think you can mention the custom plugin and the bug number in `./etc/README.md`? That way we can keep track of this.

**Comment by elopio** [comment]
@dholbach done.

**Comment by dholbach** [comment]
Brilliant, thanks!

**Pull request merged**
