### PR TITLE
Imagemagick6 update

### PR DESCRIPTION
**Pull request by wandrewkeech**
Updates the READMEs for the repo and IM6 project.

---
This change is [Reviewable](https://reviewable.io/reviews/ubuntu/snappy-playpen/84)

### CODE REVIEW

**Comment by dholbach** [comment]
This seems to include some changes from `mate-desktop`. Can you see if you can exclude them or just rebase on top of current master HEAD?

**Comment by wandrewkeech** [comment]
Yes, easily. 
I have no idea how or why I continue to get these odd downstream things, which I don't touch at all during the session, polluting my work upstream of that... particularly because I made this branch new from a `revert` of an older master, built forward in a clean fork.

**Comment by dholbach** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/84#-:-KKmDU0lAzD7huZeXhdM:1417088721)*

**Comment by dholbach** [comment]
Reviewed 3 of 8 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/84)*

**Pull request merged**
