### PR TITLE
Add the QDriverStation

### PR DESCRIPTION
**Pull request by alex-spataru**
This project generates a fully working snap of the QDriverStation. However, there are issues with the libraries that it uses (see the project's README information).

---
This change is [Reviewable](https://reviewable.io/reviews/ubuntu/snappy-playpen/79)

### CODE REVIEW

**Comment by dholbach** [comment]
Thanks a lot for your submission!

It looks like there are a number of files `qdriverstation` can't read: http://paste.ubuntu.com/17591328/ - is that an issue?

**Comment by alex-spataru** [comment]
@dholbach Yes, the QDriverStation uses SDL to get joystick input and generate sound tones. Due to AppArmor, SDL is not able to function properly in this aspect. Also, my application queries for CPU usage and Battery levels periodically (by reading `/proc/stat` and launching `upower`), however, AppArmor also seems to block those requests.

Is there any way to change my `snapcraft.yaml` file to allow my application to access these files?

**Comment by dholbach** [comment]
Can you maybe ask on `snapcraft@lists.snapcraft.io` about this?

It looks like the branch has a small conflict somewhere.

**Comment by dholbach** [comment]
*[qdriverstation/snapcraft.yaml, line 17 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/79#-KKmWgu-am2MZ6P_QYiy:-KKmWgu00SvgJYhoDTZP:1826986742) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/ef9135371abf0f7e8531f6d4c94dc2fd0f264b81/qdriverstation/snapcraft.yaml#L17)):*
> ```YAML
>       - system-observe
>       - network-observe
> ```

Maybe we need some other interfaces here too to fix some of the apparmor denials?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/79)*

**Comment by alex-spataru** [comment]
I will ask on `snapcraft@lists.snapcraft.io` to get more information about this, maybe I am missing some interfaces...

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[qdriverstation/snapcraft.yaml, line 17 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/79#-KKmWgu-am2MZ6P_QYiy:-KKnq0CD2rtHroFaiUcT:-1571646584) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/ef9135371abf0f7e8531f6d4c94dc2fd0f264b81/qdriverstation/snapcraft.yaml#L17)):*
<details><summary><i>Previously, dholbach (Daniel Holbach) wrote…</i></summary>
> Maybe we need some other interfaces here too to fix some of the apparmor denials?
</details>
It is possible that I am missing some interfaces. I will try to test with more interfaces and notify you about the results.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/79#-:-KKnpFki1lDCFspn26CF:2015998393)*

**Comment by dholbach** [comment]
*[qdriverstation/snapcraft.yaml, line 16 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/79#-KKr2Xbp3VPL2uOu77mB:-KKr2Xbq2cqELFN6QpPV:1079898338) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/ef9135371abf0f7e8531f6d4c94dc2fd0f264b81/qdriverstation/snapcraft.yaml#L16)):*
> ```YAML
>       - network-bind
>       - system-observe
>       - network-observe
> ```

As discussed earlier: maybe some interfaces are missing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/79)*

**Comment by dholbach** [comment]
*[qdriverstation/README.md, line 18 \[r2\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/79#-KLKdxRrow-wAQ-6OpEU:-KLKdxRsOxpmBTnamq_K:-1738336009) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/59cd75374133e71c805230d6b05fa9381f91050a/qdriverstation/README.md#L18)):*
> ```Markdown
> 
> - Audio & joystick input does not work.
> - The application cannot access CPU and Battery information.
> ```

Is this all still not working? I couldn't quite figure out how to use qdriverstation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/79)*

**Comment by dholbach** [comment]
Nice work. Can you maybe comment on what's working on what isn't? Is the list in `qdriverstation/README.md` up to date? Can you maybe also rebase on current master? Looks like there's a conflict in `README.md`.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/79#-:-KLKeA59AEobBwAOIJzK:-312289055)*

**Comment by alex-spataru** [comment]
Thanks,

SDL (sound + joysticks) works without any issues if the snap confinement is set to `devmode.` However, launching processes (for CPU usage and Battery status does not work). I have filled a  [bug report](https://bugs.launchpad.net/snappy/+bug/1595813) at Launchpad regarding my issue. 

According to the response that I received:

- Launching processes is allowed, however, apps were not allowed to access `/proc/stat`.
- It is possible that snapcraft will support an interface specific for `upower`, which I use to obtain battery status.

As of the time being, the list in `qdriverstation/README.md` is up to date. I will test again with the latest version of `snapcraft` and change it if needed.

I will re-base my fork to fix the conflict with `README.md`. 

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[qdriverstation/README.md, line 18 \[r2\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/79#-KLKdxRrow-wAQ-6OpEU:-KLMnh2XFWKPpwn5teYX:-222169463) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/59cd75374133e71c805230d6b05fa9381f91050a/qdriverstation/README.md#L18)):*
<details><summary><i>Previously, dholbach (Daniel Holbach) wrote…</i></summary>
> Is this all still not working? I couldn't quite figure out how to use qdriverstation.
</details>
SDL works if the confinement is set to `devmode`. I still need to figure out how to make it work in a `strict` confinement.

I will test the latest version of snapcraft and report back if needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/79#-:-KLMlxA8AzOyqeaeLtqc:-1883199507)*

**Comment by dholbach** [comment]
Nice work!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/79#-:-KLPuhzAZhOfKnPNqvKM:836320146)*

**Comment by dholbach** [comment]
Reviewed 6 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/79)*

**Comment by alex-spataru** [comment]
@dholbach Thanks for the merge and the support!

**Pull request merged**
