### PR TITLE
Add champ snap

### PR DESCRIPTION
**Pull request by dz0ny**
Champ snap which is fully working, but it needs devmode...

This change is [Reviewable](https://reviewable.io/reviews/ubuntu/snappy-playpen/166)

### CODE REVIEW

**Comment by dz0ny** [comment]
hm, is it possible that ld is picked from host, because

```
prime/
├── bin
│   ├── champ
│   ├── champ_wrapper
│   └── spinwheel
├── command-champ.wrapper
├── etc
│   └── drirc
├── lib
│   └── x86_64-linux-gnu
│       ├── libbsd.so.0 -> libbsd.so.0.8.2
│       ├── libbsd.so.0.8.2
│       ├── libexpat.so.1 -> libexpat.so.1.6.0
│       └── libexpat.so.1.6.0
├── meta
│   └── snap.yaml
└── usr
    ├── bin
    │   ├── ffmpeg
    │   └── mpv
    ├── etc
    │   └── mpv
    │       └── encoding-profiles.conf
    ├── include
    │   ├── libavcodec
    │   │   ├── avcodec.h
    │   │   ├── avdct.h
    │   │   ├── avfft.h
    │   │   ├── d3d11va.h
    │   │   ├── dirac.h
    │   │   ├── dv_profile.h
    │   │   ├── dxva2.h
    │   │   ├── jni.h
    │   │   ├── qsv.h
    │   │   ├── vaapi.h
    │   │   ├── vda.h
    │   │   ├── vdpau.h
    │   │   ├── version.h
    │   │   ├── videotoolbox.h
    │   │   ├── vorbis_parser.h
    │   │   └── xvmc.h
    │   ├── libavdevice
    │   │   ├── avdevice.h
    │   │   └── version.h
    │   ├── libavfilter
    │   │   ├── avfiltergraph.h
    │   │   ├── avfilter.h
    │   │   ├── buffersink.h
    │   │   ├── buffersrc.h
    │   │   └── version.h
    │   ├── libavformat
    │   │   ├── avformat.h
    │   │   ├── avio.h
    │   │   └── version.h
    │   ├── libavutil
    │   │   ├── adler32.h
    │   │   ├── aes_ctr.h
    │   │   ├── aes.h
    │   │   ├── attributes.h
    │   │   ├── audio_fifo.h
    │   │   ├── avassert.h
    │   │   ├── avconfig.h
    │   │   ├── avstring.h
    │   │   ├── avutil.h
    │   │   ├── base64.h
    │   │   ├── blowfish.h
    │   │   ├── bprint.h
    │   │   ├── bswap.h
    │   │   ├── buffer.h
    │   │   ├── camellia.h
    │   │   ├── cast5.h
    │   │   ├── channel_layout.h
    │   │   ├── common.h
    │   │   ├── cpu.h
    │   │   ├── crc.h
    │   │   ├── des.h
    │   │   ├── dict.h
    │   │   ├── display.h
    │   │   ├── downmix_info.h
    │   │   ├── error.h
    │   │   ├── eval.h
    │   │   ├── ffversion.h
    │   │   ├── fifo.h
    │   │   ├── file.h
    │   │   ├── frame.h
    │   │   ├── hash.h
    │   │   ├── hmac.h
    │   │   ├── hwcontext_cuda.h
    │   │   ├── hwcontext_dxva2.h
    │   │   ├── hwcontext.h
    │   │   ├── hwcontext_vaapi.h
    │   │   ├── hwcontext_vdpau.h
    │   │   ├── imgutils.h
    │   │   ├── intfloat.h
    │   │   ├── intreadwrite.h
    │   │   ├── lfg.h
    │   │   ├── log.h
    │   │   ├── lzo.h
    │   │   ├── macros.h
    │   │   ├── mastering_display_metadata.h
    │   │   ├── mathematics.h
    │   │   ├── md5.h
    │   │   ├── mem.h
    │   │   ├── motion_vector.h
    │   │   ├── murmur3.h
    │   │   ├── opt.h
    │   │   ├── parseutils.h
    │   │   ├── pixdesc.h
    │   │   ├── pixelutils.h
    │   │   ├── pixfmt.h
    │   │   ├── random_seed.h
    │   │   ├── rational.h
    │   │   ├── rc4.h
    │   │   ├── replaygain.h
    │   │   ├── ripemd.h
    │   │   ├── samplefmt.h
    │   │   ├── sha512.h
    │   │   ├── sha.h
    │   │   ├── stereo3d.h
    │   │   ├── tea.h
    │   │   ├── threadmessage.h
    │   │   ├── timecode.h
    │   │   ├── time.h
    │   │   ├── timestamp.h
    │   │   ├── tree.h
    │   │   ├── twofish.h
    │   │   ├── version.h
    │   │   └── xtea.h
    │   ├── libpostproc
    │   │   ├── postprocess.h
    │   │   └── version.h
    │   ├── libswresample
    │   │   ├── swresample.h
    │   │   └── version.h
    │   ├── libswscale
    │   │   ├── swscale.h
    │   │   └── version.h
    │   └── mpv
    │       ├── client.h
    │       ├── opengl_cb.h
    │       └── qthelper.hpp
``

**Comment by dholbach** [comment]
It fails to build in Travis: https://travis-ci.org/ubuntu/snappy-playpen/builds/144375356 - maybe this is because of https://bugs.launchpad.net/snapcraft/+bug/1595243 which is fixed in the upcoming snapcraft 2.12.1?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/166#-:-KMYhMdN8X0-zB5RH464:994503650)*

**Comment by dholbach** [comment]
*[champ/snapcraft.yaml, line 12 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/166#-KMYhyFwtmEB-Q-vbx48:-KMYhyFxQW9dFkMR1k3t:1086736865) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/892c5548168451b3ba0deaf5d66dec0ec30ba111/champ/snapcraft.yaml#L12)):*
> ```YAML
> 
> parts:
>   ffmpeg:
> ```

Could the ffmpeg remote part be used? https://wiki.ubuntu.com/snapcraft/parts

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/166)*

**Comment by dholbach** [comment]
*[champ/champ_wrapper, line 33 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/166#-KMYi7OWen-qndf_a-h7:-KMYi7OWen-qndf_a-h8:1208828047) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/892c5548168451b3ba0deaf5d66dec0ec30ba111/champ/champ_wrapper#L33)):*
> ```
> export LD_LIBRARY_PATH=$SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH
> 
> exec "$SNAP/bin/champ" "$*"
> ```

Do you know how much of this wrapper is required?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/166)*

**Comment by dholbach** [comment]
*[champ/champ_wrapper, line 33 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/166#-KMYi7OWen-qndf_a-h7:-KMYiJT-gGg9zzV0b1UV:-1352189991) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/892c5548168451b3ba0deaf5d66dec0ec30ba111/champ/champ_wrapper#L33)):*
<details><summary><i>Previously, dholbach (Daniel Holbach) wrote…</i></summary>
> Do you know how much of this wrapper is required?
</details>
I'm asking because I'd be interested to know if any of the common desktop launchers would work? (http://insights.ubuntu.com/2016/07/06/ubuntu-app-developer-blog-announcing-new-snap-desktop-launchers/)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/166)*

**Comment by dholbach** [comment]
*[champ/parts/plugins/x-gosrc.py, line 47 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/166#-KMYiggdT02Z11lj0XJB:-KMYiggeiBRZcDTFhbBV:284949316) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/892c5548168451b3ba0deaf5d66dec0ec30ba111/champ/parts/plugins/x-gosrc.py#L47)):*
> ```Python
> 
> 
> class GoPlugin(snapcraft.BasePlugin):
> ```

Could this inherit from the GoPlugin instead to duplicate less code?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/166)*

**Comment by dz0ny** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[champ/snapcraft.yaml, line 12 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/166#-KMYhyFwtmEB-Q-vbx48:-KM_kqYWVSY0AMqcrYCC:619624662) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/892c5548168451b3ba0deaf5d66dec0ec30ba111/champ/snapcraft.yaml#L12)):*
<details><summary><i>Previously, dholbach (Daniel Holbach) wrote…</i></summary>
> Could the ffmpeg remote part be used? https://wiki.ubuntu.com/snapcraft/parts
</details>
Can I change build params? also it seems it builds from master, I need at least locked to latest release

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/166)*

**Comment by dz0ny** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[champ/parts/plugins/x-gosrc.py, line 47 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/166#-KMYiggdT02Z11lj0XJB:-KM_lDHJMkGLKy_KyGeV:-2091484775) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/892c5548168451b3ba0deaf5d66dec0ec30ba111/champ/parts/plugins/x-gosrc.py#L47)):*
<details><summary><i>Previously, dholbach (Daniel Holbach) wrote…</i></summary>
> Could this inherit from the GoPlugin instead to duplicate less code?
</details>
Nope it's specific to CGo+Go+MPV build

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/166)*

**Comment by dz0ny** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[champ/champ_wrapper, line 33 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/166#-KMYi7OWen-qndf_a-h7:-KM_lRn1XWKuSL6N-SBE:-1015753884) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/892c5548168451b3ba0deaf5d66dec0ec30ba111/champ/champ_wrapper#L33)):*
<details><summary><i>Previously, dholbach (Daniel Holbach) wrote…</i></summary>
> I'm asking because I'd be interested to know if any of the common desktop launchers would work? (http://insights.ubuntu.com/2016/07/06/ubuntu-app-developer-blog-announcing-new-snap-desktop-launchers/)
</details>
I does not seem that anyone would support  runtime library path?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/166)*

**Comment by dz0ny** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[champ/champ_wrapper, line 33 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/166#-KMYi7OWen-qndf_a-h7:-KMcKshslRhaj-YBxABz:790154128) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/892c5548168451b3ba0deaf5d66dec0ec30ba111/champ/champ_wrapper#L33)):*
<details><summary><i>Previously, dz0ny (Janez Troha) wrote…</i></summary>
> I does not seem that anyone would support  runtime library path?
</details>
Cleaned up to bare minimal

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/166)*

**Comment by dz0ny** [comment]
Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/166)*

**Comment by dz0ny** [comment]
Part of project now https://github.com/dz0ny/champ/tree/master/packaging/snap-x86/champ, thanks for help :)

**Comment by dholbach** [comment]
I think I'm happy for this to be merged. Did you close this PR for a specific reason?

**Pull request closed without merging**
