### PR TITLE
Add the MirageOS snap.

### PR DESCRIPTION
**Pull request by elopio**
This change is [Reviewable](https://reviewable.io/reviews/ubuntu/snappy-playpen/158)

### CODE REVIEW

**Comment by dholbach** [comment]
*[mirageos/README.md, line 20 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/158#-KMYlDFGjpO-DZQAJqrb:-KMYlDFHbmNCUJzWY3R1:1694300923) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/4669ad8b7a7f193e4ecc3b26b471355e706b05c7/mirageos/README.md#L20)):*
> ```Markdown
>    file. There must be a way to install from this file, instead of redefining
>    the dependencies, install them and call make. If we find how to do this,
>    the plugin can be upstreamed to snapcraft.
> ```

Nice one! Maybe you can file a bug on the Snappy Playpen once this lands, so we can track this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/158)*

**Comment by dholbach** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/158#-:-KMYmx99Xp9esEz4F6TG:1417088721)*

**Comment by dholbach** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/158)*

**Comment by elopio** [comment]
@dholbach reported: https://bugs.launchpad.net/snapcraft/+bug/1602733

**Pull request merged**
