### PR TITLE
Mutt snap

### PR DESCRIPTION
**Pull request by tsimonq2**
This adds a working Mutt snap.

---

This change is [Reviewable](https://reviewable.io/reviews/ubuntu/snappy-playpen/98)

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/ubuntu/snappy-playpen/pull/98%23issuecomment-227410143%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/98%23issuecomment-227410345%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/98%23issuecomment-227410642%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/98%23issuecomment-227411329%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/98%23issuecomment-227412622%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/98%23issuecomment-227412826%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/98%23issuecomment-227421805%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/98%23issuecomment-227758523%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/98%23issuecomment-227918718%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/98%23issuecomment-227957561%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/98%23issuecomment-228672302%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/98%23issuecomment-228672461%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/98%23issuecomment-228944908%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/98%23issuecomment-228945074%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/98%23issuecomment-228957322%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/98%23issuecomment-232615408%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/98%23issuecomment-227410143%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%5Cn%5Cn%5Cn%5CnReviewed%202%20of%202%20files%20at%20r1.%5CnReview%20status%3A%20all%20files%20reviewed%20at%20latest%20revision%2C%20all%20discussions%20resolved.%5Cn%5Cn---%5Cn%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/98%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-06-21T11%3A15%3A02Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1823296%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/didrocks%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%5Cn%5Cn%5CnReview%20status%3A%20all%20files%20reviewed%20at%20latest%20revision%2C%201%20unresolved%20discussion%2C%20all%20commit%20checks%20successful.%5Cn%5Cn---%5Cn%5Cn%2A%5Ba%20discussion%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/98%23-KKmf6E0Wd-Tuo7NSs7D%3A-KKmf6E0Wd-Tuo7NSs7E%3A1539809997%29%20%28no%20related%20file%29%3A%2A%5CnCan%20you%20add%20it%20to%20the%20main%20content%20table%2C%20please%3F%5Cn%5Cn---%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/98%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-06-21T11%3A16%3A05Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1823296%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/didrocks%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40didrocks%20done%22%2C%20%22created_at%22%3A%20%222016-06-21T11%3A17%3A43Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3689821%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tsimonq2%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Cimg%20class%3D%5C%22emoji%5C%22%20title%3D%5C%22%3Algtm%3A%5C%22%20alt%3D%5C%22%3Algtm%3A%5C%22%20align%3D%5C%22absmiddle%5C%22%20src%3D%5C%22https%3A//reviewable.io/lgtm.png%5C%22%20height%3D%5C%2220%5C%22%20width%3D%5C%2261%5C%22/%3E%5Cn%5Cn---%5Cn%5CnReviewed%201%20of%201%20files%20at%20r2.%5CnReview%20status%3A%20all%20files%20reviewed%20at%20latest%20revision%2C%201%20unresolved%20discussion.%5Cn%5Cn---%5Cn%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/98%23-%3A-KKmgHbsKdfmAicf9toO%3A1417088721%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-06-21T11%3A21%3A11Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1823296%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/didrocks%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%2A%5Bmutt/README.md%2C%20line%208%20%5C%5C%5Br1%5C%5C%5D%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/98%23-KKmhm7x-XQg1ES1wv_J%3A-KKmhm7x-XQg1ES1wv_K%3A-1683362262%29%20%28%5Braw%20file%5D%28https%3A//github.com/ubuntu/snappy-playpen/blob/41f69f022a8ce679685a210f2011474e1d530523/mutt/README.md%23L8%29%29%3A%2A%5Cn%3E%20%60%60%60Markdown%5Cn%3E%20%5Cn%3E%20Working%20features%3A%5Cn%3E%20%20-%20Fully%20functional%20it%20seems%5Cn%3E%20%60%60%60%5Cn%5CnNot%20quite.%20The%20group%20creation%20will%20not%20work%20and%20access%20to%20files%20in%20%60%7E%60%20won%27t%20be%20as%20straight-forward%20as%20in%20normal%20mutt.%20Maybe%20ask%20some%20real%20users%20to%20test%3F%5Cn%5Cn---%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/98%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-06-21T11%3A28%3A21Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20would%20hold%20off%20for%20now.%5Cn%5Cn---%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/98%23-%3A-KKmiAiz0JP6eqY31ONR%3A1759677850%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-06-21T11%3A29%3A28Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%2A%5Bmutt/README.md%2C%20line%208%20%5C%5C%5Br1%5C%5C%5D%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/98%23-KKmhm7x-XQg1ES1wv_J%3A-KKmsduGMZ-nRRF0zxOa%3A935765301%29%20%28%5Braw%20file%5D%28https%3A//github.com/ubuntu/snappy-playpen/blob/41f69f022a8ce679685a210f2011474e1d530523/mutt/README.md%23L8%29%29%3A%2A%5Cn%3Cdetails%3E%3Csummary%3E%3Ci%3EPreviously%2C%20dholbach%20%28Daniel%20Holbach%29%20wrote%5Cu2026%3C/i%3E%3C/summary%3E%5Cn%3E%20Not%20quite.%20The%20group%20creation%20will%20not%20work%20and%20access%20to%20files%20in%20%60%7E%60%20won%27t%20be%20as%20straight-forward%20as%20in%20normal%20mutt.%20Maybe%20ask%20some%20real%20users%20to%20test%3F%5Cn%3C/details%3E%5CnNeeds%20some%20discussion%20on%20the%20list%20to%20understand%20problems%20better.%5Cn%5Cn---%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/98%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-06-21T12%3A15%3A27Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%5Cn%5Cn%5CnReview%20status%3A%201%20of%204%20files%20reviewed%20at%20latest%20revision%2C%203%20unresolved%20discussions.%5Cn%5Cn---%5Cn%5Cn%2A%5Ba%20discussion%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/98%23-KKsT32vuIFzGhed-Mmx%3A-KKsT32vuIFzGhed-Mmy%3A-203429267%29%20%28no%20related%20file%29%3A%2A%5CnThanks%20for%20the%20changes%21%5Cn%5CnAs%20told%20on%20IRC%2C%20I%20think%20we%20shouldn%27t%20%20fork%20the%20autotools%20plugin%20from%20snapcraft%20but%20either%3A%5Cn%2A%20add%20some%20parameters%20with%20upstream%20to%20tweak%20the%20%5C%22make%5C%22%20commands%5Cn%2A%20or%20have%20that%20extensable%20by%20a%20dedicated%20plugin%20%28which%20inherit%20from%20autools%29%20which%20is%20changing%20only%20the%20%5C%22make%5C%22%20commands%20in%20fakeroot%20make%20%3B%29%5Cn%5Cn---%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/98%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-06-22T14%3A18%3A32Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1823296%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/didrocks%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40didrocks%20how%20would%20I%20accomplish%20the%20latter%3F%20how%20would%20I%20inherit%20from%20the%20Autotools%20plugin%20but%20only%20tweak%20a%20tiny%20thing%20without%20forking%3F%22%2C%20%22created_at%22%3A%20%222016-06-23T00%3A41%3A31Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3689821%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tsimonq2%22%7D%7D%2C%20%7B%22body%22%3A%20%22What%20you%20need%20to%20do%20is%20to%20propose%20a%20fix%20on%20the%20upstream%20autotools%20snapcraft%20plugin%20to%20make%20it%20configurable/inheritable%20that%20way%20%28so%20that%20you%20can%20tweak%20each%20commands%29%5Cn%5Cn---%5Cn%5CnReview%20status%3A%201%20of%204%20files%20reviewed%20at%20latest%20revision%2C%203%20unresolved%20discussions.%5Cn%5Cn---%5Cn%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/98%23-%3A-KKvpqb78ax-p-wndgtD%3A-746497168%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-06-23T06%3A00%3A02Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1823296%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/didrocks%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%2A%5Bmutt/parts/plugins/autotoolscustom.py%2C%20line%206%20%5C%5C%5Br4%5C%5C%5D%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/98%23-KLFkIGyhmQtJ_IpnC3R%3A-KLFkIGzaGiaKuyYT6FK%3A144601301%29%20%28%5Braw%20file%5D%28https%3A//github.com/ubuntu/snappy-playpen/blob/3a3bebad5bded20c4f4a90224c6831c510822c6c/mutt/parts/plugins/autotoolscustom.py%23L6%29%29%3A%2A%5Cn%3E%20%60%60%60Python%5Cn%3E%20%5Cn%3E%20class%20AutotoolscustomPlugin%28snapcraft.BasePlugin%29%3A%5Cn%3E%20%60%60%60%5Cn%5CnCould%20this%20inherit%20from%20%60snapcraft.plugins.autotools.AutotoolsPlugin%60%20instead%3F%20This%20would%20probably%20avoid%20some%20of%20the%20duplication%20in%20here.%5Cn%5Cn---%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/98%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-06-27T07%3A27%3A57Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%2A%5Bmutt/README.md%2C%20line%208%20%5C%5C%5Br1%5C%5C%5D%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/98%23-KKmhm7x-XQg1ES1wv_J%3A-KLFke1kC-c3ID8lncqU%3A-1290065134%29%20%28%5Braw%20file%5D%28https%3A//github.com/ubuntu/snappy-playpen/blob/41f69f022a8ce679685a210f2011474e1d530523/mutt/README.md%23L8%29%29%3A%2A%5Cn%3Cdetails%3E%3Csummary%3E%3Ci%3EPreviously%2C%20dholbach%20%28Daniel%20Holbach%29%20wrote%5Cu2026%3C/i%3E%3C/summary%3E%5Cn%3E%20Needs%20some%20discussion%20on%20the%20list%20to%20understand%20problems%20better.%5Cn%3C/details%3E%5CnApparently%20mutt%20is%20working%20for%20mvo%3F%5Cn%5Cn---%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/98%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-06-27T07%3A28%3A58Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%2C%20%7B%22body%22%3A%20%22yes%20%40dholbach%22%2C%20%22created_at%22%3A%20%222016-06-28T04%3A24%3A35Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3689821%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tsimonq2%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40dholbach%20%40didrocks%20How%20would%20I%20go%20about%20inheriting%20the%20autotools%20plugin%20then%20modifying%20the%20command%20to%20include%20fakeroot%3F%22%2C%20%22created_at%22%3A%20%222016-06-28T04%3A26%3A12Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3689821%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tsimonq2%22%7D%7D%2C%20%7B%22body%22%3A%20%22you%20need%20to%20patch%20upstream%20snapcraft%20to%20be%20extendible%20for%20it%20IMHO.%22%2C%20%22created_at%22%3A%20%222016-06-28T06%3A09%3A43Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1823296%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/didrocks%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40tsimonq2%20have%20you%20had%20the%20chance%20to%20look%20at%20this%3F%20Anything%20you%20need%20help%20moving%20this%20PR%20forward%3F%22%2C%20%22created_at%22%3A%20%222016-07-14T09%3A32%3A42Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1689781%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dplanella%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/ubuntu/snappy-playpen/pull/98#issuecomment-227410143'>General Comment</a></b>
- <a href='https://github.com/didrocks'></a> Reviewed 2 of 2 files at r1.
  Review status: all files reviewed at latest revision, all discussions resolved.
  ---
  _Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98)_
  
## \- <a href='https://github.com/didrocks'></a> Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

_[a discussion](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98#-KKmf6E0Wd-Tuo7NSs7D:-KKmf6E0Wd-Tuo7NSs7E:1539809997) (no related file):_
## Can you add it to the main content table, please?

_Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98)_

- <a href='https://github.com/tsimonq2'></a> @didrocks done
## \- <a href='https://github.com/didrocks'></a> :lgtm:

Reviewed 1 of 1 files at r2.
## Review status: all files reviewed at latest revision, 1 unresolved discussion.

_Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98#-:-KKmgHbsKdfmAicf9toO:1417088721)_

- <a href='https://github.com/dholbach'></a> _[mutt/README.md, line 8 [r1]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98#-KKmhm7x-XQg1ES1wv_J:-KKmhm7x-XQg1ES1wv_K:-1683362262) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/41f69f022a8ce679685a210f2011474e1d530523/mutt/README.md#L8)):_
  > `Markdown
  >
  > Working features:
  >  - Fully functional it seems
  >`
  Not quite. The group creation will not work and access to files in `~` won't be as straight-forward as in normal mutt. Maybe ask some real users to test?
  ---
  _Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98)_
  
## \- <a href='https://github.com/dholbach'></a> I would hold off for now.

_Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98#-:-KKmiAiz0JP6eqY31ONR:1759677850)_

- <a href='https://github.com/dholbach'></a> _[mutt/README.md, line 8 [r1]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98#-KKmhm7x-XQg1ES1wv_J:-KKmsduGMZ-nRRF0zxOa:935765301) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/41f69f022a8ce679685a210f2011474e1d530523/mutt/README.md#L8)):_
  <details><summary>
  
  <i>Previously, dholbach (Daniel Holbach) wrote…</i></summary>
  
  
  > Not quite. The group creation will not work and access to files in `~` won't be as straight-forward as in normal mutt. Maybe ask some real users to test?
  </details>
  Needs some discussion on the list to understand problems better.
  ---
  _Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98)_
  
## \- <a href='https://github.com/didrocks'></a> Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

_[a discussion](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98#-KKsT32vuIFzGhed-Mmx:-KKsT32vuIFzGhed-Mmy:-203429267) (no related file):_
Thanks for the changes!
As told on IRC, I think we shouldn't  fork the autotools plugin from snapcraft but either:
- add some parameters with upstream to tweak the "make" commands
## \* or have that extensable by a dedicated plugin (which inherit from autools) which is changing only the "make" commands in fakeroot make ;)

_Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98)_

- <a href='https://github.com/tsimonq2'></a> @didrocks how would I accomplish the latter? how would I inherit from the Autotools plugin but only tweak a tiny thing without forking?
## Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

_Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98#-:-KKvpqb78ax-p-wndgtD:-746497168)_

- <a href='https://github.com/dholbach'></a> _[mutt/parts/plugins/autotoolscustom.py, line 6 [r4]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98#-KLFkIGyhmQtJ_IpnC3R:-KLFkIGzaGiaKuyYT6FK:144601301) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/3a3bebad5bded20c4f4a90224c6831c510822c6c/mutt/parts/plugins/autotoolscustom.py#L6)):_
  > `Python
  >
  > class AutotoolscustomPlugin(snapcraft.BasePlugin):
  >`
  Could this inherit from `snapcraft.plugins.autotools.AutotoolsPlugin` instead? This would probably avoid some of the duplication in here.
  ---
  _Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98)_
  
- <a href='https://github.com/dholbach'></a> _[mutt/README.md, line 8 [r1]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98#-KKmhm7x-XQg1ES1wv_J:-KLFke1kC-c3ID8lncqU:-1290065134) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/41f69f022a8ce679685a210f2011474e1d530523/mutt/README.md#L8)):_
  <details><summary>
  
  <i>Previously, dholbach (Daniel Holbach) wrote…</i></summary>
  
  
  > Needs some discussion on the list to understand problems better.
  </details>
  Apparently mutt is working for mvo?
  ---
  _Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98)_
  
- <a href='https://github.com/tsimonq2'></a> yes @dholbach
- <a href='https://github.com/tsimonq2'></a> @dholbach @didrocks How would I go about inheriting the autotools plugin then modifying the command to include fakeroot?
- <a href='https://github.com/didrocks'></a> you need to patch upstream snapcraft to be extendible for it IMHO.
- <a href='https://github.com/dplanella'></a> @tsimonq2 have you had the chance to look at this? Anything you need help moving this PR forward?

<a href='https://www.codereviewhub.com/ubuntu/snappy-playpen/pull/98?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/ubuntu/snappy-playpen/pull/98?approve=1'></a>&nbsp;<a href='https://github.com/ubuntu/snappy-playpen/pull/98'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by didrocks** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98)*

**Comment by didrocks** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98#-KKmf6E0Wd-Tuo7NSs7D:-KKmf6E0Wd-Tuo7NSs7E:1539809997) (no related file):*
Can you add it to the main content table, please?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98)*

**Comment by tsimonq2** [comment]
@didrocks done

**Comment by didrocks** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98#-:-KKmgHbsKdfmAicf9toO:1417088721)*

**Comment by dholbach** [comment]
*[mutt/README.md, line 8 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98#-KKmhm7x-XQg1ES1wv_J:-KKmhm7x-XQg1ES1wv_K:-1683362262) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/41f69f022a8ce679685a210f2011474e1d530523/mutt/README.md#L8)):*
> ```Markdown
> 
> Working features:
>  - Fully functional it seems
> ```

Not quite. The group creation will not work and access to files in `~` won't be as straight-forward as in normal mutt. Maybe ask some real users to test?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98)*

**Comment by dholbach** [comment]
I would hold off for now.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98#-:-KKmiAiz0JP6eqY31ONR:1759677850)*

**Comment by dholbach** [comment]
*[mutt/README.md, line 8 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98#-KKmhm7x-XQg1ES1wv_J:-KKmsduGMZ-nRRF0zxOa:935765301) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/41f69f022a8ce679685a210f2011474e1d530523/mutt/README.md#L8)):*
<details><summary><i>Previously, dholbach (Daniel Holbach) wrote…</i></summary>
> Not quite. The group creation will not work and access to files in `~` won't be as straight-forward as in normal mutt. Maybe ask some real users to test?
</details>
Needs some discussion on the list to understand problems better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98)*

**Comment by didrocks** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98#-KKsT32vuIFzGhed-Mmx:-KKsT32vuIFzGhed-Mmy:-203429267) (no related file):*
Thanks for the changes!

As told on IRC, I think we shouldn't  fork the autotools plugin from snapcraft but either:
* add some parameters with upstream to tweak the "make" commands
* or have that extensable by a dedicated plugin (which inherit from autools) which is changing only the "make" commands in fakeroot make ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98)*

**Comment by tsimonq2** [comment]
@didrocks how would I accomplish the latter? how would I inherit from the Autotools plugin but only tweak a tiny thing without forking?

**Comment by didrocks** [comment]
What you need to do is to propose a fix on the upstream autotools snapcraft plugin to make it configurable/inheritable that way (so that you can tweak each commands)

---

Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98#-:-KKvpqb78ax-p-wndgtD:-746497168)*

**Comment by dholbach** [comment]
*[mutt/parts/plugins/autotoolscustom.py, line 6 \[r4\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98#-KLFkIGyhmQtJ_IpnC3R:-KLFkIGzaGiaKuyYT6FK:144601301) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/3a3bebad5bded20c4f4a90224c6831c510822c6c/mutt/parts/plugins/autotoolscustom.py#L6)):*
> ```Python
> 
> class AutotoolscustomPlugin(snapcraft.BasePlugin):
> ```

Could this inherit from `snapcraft.plugins.autotools.AutotoolsPlugin` instead? This would probably avoid some of the duplication in here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98)*

**Comment by dholbach** [comment]
*[mutt/README.md, line 8 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98#-KKmhm7x-XQg1ES1wv_J:-KLFke1kC-c3ID8lncqU:-1290065134) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/41f69f022a8ce679685a210f2011474e1d530523/mutt/README.md#L8)):*
<details><summary><i>Previously, dholbach (Daniel Holbach) wrote…</i></summary>
> Needs some discussion on the list to understand problems better.
</details>
Apparently mutt is working for mvo?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/98)*

**Comment by tsimonq2** [comment]
yes @dholbach

**Comment by tsimonq2** [comment]
@dholbach @didrocks How would I go about inheriting the autotools plugin then modifying the command to include fakeroot?

**Comment by didrocks** [comment]
you need to patch upstream snapcraft to be extendible for it IMHO.

**Comment by dplanella** [comment]
@tsimonq2 have you had the chance to look at this? Anything you need help moving this PR forward?

**Pull request closed without merging**
