### PR TITLE
Adding etherpad-lite snapping project (WIP)

### PR DESCRIPTION
**Pull request by Winael**
To add etherpad-lite snapping project, currently in WIP

---

This change is [Reviewable](https://reviewable.io/reviews/ubuntu/snappy-playpen/32)

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/ubuntu/snappy-playpen/pull/32%23issuecomment-224196847%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/32%23issuecomment-224203312%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/32%23issuecomment-224210323%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/32%23issuecomment-224456667%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/32%23issuecomment-224835814%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/32%23issuecomment-227403692%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/32%23issuecomment-227466076%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/32%23issuecomment-224196847%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Nice%20work%21%20Quick%20question%3A%20you%20mention%20it%20is%20work%20in%20progress%20-%20could%20you%20add%20some%20information%20on%20the%20README.md%20file%20about%20what%27s%20working%20and%20what%27s%20not%3F%20Also%20it%27d%20be%20good%20to%20list%20any%20known%20issues%20there%20too.%20Thanks%21%22%2C%20%22created_at%22%3A%20%222016-06-07T07%3A01%3A04Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1689781%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dplanella%22%7D%7D%2C%20%7B%22body%22%3A%20%22Hi%20David%2C%5Cr%5Cn%5Cr%5CnI%20update%20the%20README.md.%20Actually%20I%20ned%20to%20copy%20entire%20folder%20from%20%60parts/etherpad-lite/src%60%20%28pulled%20from%20github%29%20to%20the%20%60./snap/%60%20folder%29.%20I%20talk%20about%20it%20to%20%40didrocks%20at%20UbuCon%20Paris.%20%5Cr%5Cn%5Cr%5CnI%27m%20working%20again%20on%20this%20project%20that%20I%20leave%20the%20time%20I%20create%20my%20first%20snapcraft%20video%20tutorial%20%28in%20French%29.%20%5Cr%5Cn%5Cr%5CnNow%20with%20Playpen%2C%20it%20will%20be%20more%20easely%20to%20work%20on%20it%20and%20collaborate%20with%20people%2C%20exchange%20and%20learn.%20README.md%20file%20will%20be%20the%20base%20of%20a%20blogpost%20on%20how%20to%20snapcraft%20for%20noobs%20like%20me%20%5E%5E%20%5Cr%5Cn%5Cr%5CnCheers%22%2C%20%22created_at%22%3A%20%222016-06-07T07%3A36%3A32Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5644057%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Winael%22%7D%7D%2C%20%7B%22body%22%3A%20%22Excellent%21%20Join%20us%20on%20https%3A//gitter.im/ubuntu/snappy-playpen%20whenever%20you%27ve%20got%20time%20and%20let%27s%20work%20together%20on%20this%21%22%2C%20%22created_at%22%3A%20%222016-06-07T08%3A11%3A32Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1689781%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dplanella%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20had%20a%20go%20at%20it%2C%20and%20proposed%20some%20changes%20to%20your%20branch%20here%3A%20https%3A//github.com/Winael/snappy-playpen-1/pull/1%22%2C%20%22created_at%22%3A%20%222016-06-08T00%3A47%3A16Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1689781%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dplanella%22%7D%7D%2C%20%7B%22body%22%3A%20%22Current%20status%3A%5Cr%5Cn%5Cr%5Cn%60%60%60%5Cr%5Cn%24%20sudo%20/snap/bin/etherpad-lite-unofficial.etherpad-lite%20%5Cr%5Cn%2B%20cd%20/var/snap/etherpad-lite-unofficial/100001%5Cr%5Cn%2B%20exec%20/snap/etherpad-lite-unofficial/100001/bin/etherpad-lite%20--settings%20/snap/etherpad-lite-unofficial/100001/etc/settings.json%5Cr%5Cn%5B2016-06-08%2013%3A07%3A55.716%5D%20%5BWARN%5D%20console%20-%20DirtyDB%20is%20used.%20This%20is%20fine%20for%20testing%20but%20not%20recommended%20for%20production.%5Cr%5Cn%5B2016-06-08%2013%3A07%3A58.216%5D%20%5BERROR%5D%20console%20-%20Failed%20to%20load%20%27/snap/etherpad-lite-unofficial/100001/lib/node_modules/ep_etherpad-lite/node/hooks/express/static%3AexpressCreateServer%27%20for%20%27ep_etherpad-lite/static/hooks/expressCreateServer%27%3A%20Error%3A%20ENOENT%3A%20no%20such%20file%20or%20directory%2C%20stat%20%27/snap/etherpad-lite-unofficial/100001/lib/var/%27%5Cr%5Cn%60%60%60%5Cr%5Cn-%20It%20seems%20something%20%5Bin%20this%20module%5D%28https%3A//github.com/ether/etherpad-lite/blob/develop/src/node/hooks/express/static.js%29%20is%20trying%20to%20write%20to%20%60%24SNAP/lib/var%60%5Cr%5Cn%5Cr%5CnNotes%3A%20as%20per%20the%20discussion%20on%20https%3A//github.com/Winael/snappy-playpen-1/pull/1%2C%20we%20need%20to%20look%20at%3A%5Cr%5Cn%5Cr%5Cn-%20asac%27s%20upstream%20branch%20at%20https%3A//github.com/asac/etherpad-lite/commits/snap-support%5Cr%5Cn-%20https%3A//github.com/asac/etherpad-lite/commit/d3e12b31e4542eb637b33f2fbbad265d7116e38f%5Cr%5Cn-%20https%3A//github.com/asac/etherpad-lite/commit/8e62911cb2f6be278f70d11c2dc8492e22782f2a%22%2C%20%22created_at%22%3A%20%222016-06-09T08%3A48%3A04Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1689781%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dplanella%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%2A%5Betherpad-lite/README.md%2C%20line%205%20%5C%5C%5Br6%5C%5C%5D%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/32%23-KKmY3aQM4lJ7nthchZQ%3A-KKmY3aR7SmF_go7wDcu%3A1185909849%29%20%28%5Braw%20file%5D%28https%3A//github.com/ubuntu/snappy-playpen/blob/03cdd460859890e7ec8e31d06bc411121a92f5de/etherpad-lite/README.md%23L5%29%29%3A%2A%5Cn%3E%20%60%60%60Markdown%5Cn%3E%20title%3A%20Etherpad-lite%5Cn%3E%20author%3A%20Winael%5Cn%3E%20status%3A%20WIP.%20Not%20working%5Cn%3E%20%60%60%60%5Cn%5CnWe%20are%20still%20blocked%20here.%5Cn%5Cn---%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/32%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-06-21T10%3A40%3A53Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%2C%20%7B%22body%22%3A%20%22It%20seems%20that%20I%20have%20commit%20in%20the%20wrong%20place%20sorry%20%5E%5E%20%22%2C%20%22created_at%22%3A%20%222016-06-21T14%3A55%3A35Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5644057%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Winael%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/ubuntu/snappy-playpen/pull/32#issuecomment-224196847'>General Comment</a></b>
- <a href='https://github.com/dplanella'></a> Nice work! Quick question: you mention it is work in progress - could you add some information on the README.md file about what's working and what's not? Also it'd be good to list any known issues there too. Thanks!
- <a href='https://github.com/Winael'></a> Hi David,
  I update the README.md. Actually I ned to copy entire folder from `parts/etherpad-lite/src` (pulled from github) to the `./snap/` folder). I talk about it to @didrocks at UbuCon Paris.
  I'm working again on this project that I leave the time I create my first snapcraft video tutorial (in French).
  Now with Playpen, it will be more easely to work on it and collaborate with people, exchange and learn. README.md file will be the base of a blogpost on how to snapcraft for noobs like me ^^
  Cheers
- <a href='https://github.com/dplanella'></a> Excellent! Join us on https://gitter.im/ubuntu/snappy-playpen whenever you've got time and let's work together on this!
- <a href='https://github.com/dplanella'></a> I had a go at it, and proposed some changes to your branch here: https://github.com/Winael/snappy-playpen-1/pull/1
- <a href='https://github.com/dplanella'></a> Current status:

```
$ sudo /snap/bin/etherpad-lite-unofficial.etherpad-lite
+ cd /var/snap/etherpad-lite-unofficial/100001
+ exec /snap/etherpad-lite-unofficial/100001/bin/etherpad-lite --settings /snap/etherpad-lite-unofficial/100001/etc/settings.json
[2016-06-08 13:07:55.716] [WARN] console - DirtyDB is used. This is fine for testing but not recommended for production.
[2016-06-08 13:07:58.216] [ERROR] console - Failed to load '/snap/etherpad-lite-unofficial/100001/lib/node_modules/ep_etherpad-lite/node/hooks/express/static:expressCreateServer' for 'ep_etherpad-lite/static/hooks/expressCreateServer': Error: ENOENT: no such file or directory, stat '/snap/etherpad-lite-unofficial/100001/lib/var/'
```
- It seems something [in this module](https://github.com/ether/etherpad-lite/blob/develop/src/node/hooks/express/static.js) is trying to write to `$SNAP/lib/var`
  Notes: as per the discussion on https://github.com/Winael/snappy-playpen-1/pull/1, we need to look at:
- asac's upstream branch at https://github.com/asac/etherpad-lite/commits/snap-support
- https://github.com/asac/etherpad-lite/commit/d3e12b31e4542eb637b33f2fbbad265d7116e38f
- https://github.com/asac/etherpad-lite/commit/8e62911cb2f6be278f70d11c2dc8492e22782f2a
- <a href='https://github.com/dholbach'></a> _[etherpad-lite/README.md, line 5 [r6]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/32#-KKmY3aQM4lJ7nthchZQ:-KKmY3aR7SmF_go7wDcu:1185909849) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/03cdd460859890e7ec8e31d06bc411121a92f5de/etherpad-lite/README.md#L5)):_
  > `Markdown
  > title: Etherpad-lite
  > author: Winael
  > status: WIP. Not working
  >`
  We are still blocked here.
  ---
  _Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/32)_
  
- <a href='https://github.com/Winael'></a> It seems that I have commit in the wrong place sorry ^^

<a href='https://www.codereviewhub.com/ubuntu/snappy-playpen/pull/32?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/ubuntu/snappy-playpen/pull/32?approve=1'></a>&nbsp;<a href='https://github.com/ubuntu/snappy-playpen/pull/32'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dplanella** [comment]
Nice work! Quick question: you mention it is work in progress - could you add some information on the README.md file about what's working and what's not? Also it'd be good to list any known issues there too. Thanks!

**Comment by Winael** [comment]
Hi David,

I update the README.md. Actually I ned to copy entire folder from `parts/etherpad-lite/src` (pulled from github) to the `./snap/` folder). I talk about it to @didrocks at UbuCon Paris. 

I'm working again on this project that I leave the time I create my first snapcraft video tutorial (in French). 

Now with Playpen, it will be more easely to work on it and collaborate with people, exchange and learn. README.md file will be the base of a blogpost on how to snapcraft for noobs like me ^^ 

Cheers

**Comment by dplanella** [comment]
Excellent! Join us on https://gitter.im/ubuntu/snappy-playpen whenever you've got time and let's work together on this!

**Comment by dplanella** [comment]
I had a go at it, and proposed some changes to your branch here: https://github.com/Winael/snappy-playpen-1/pull/1

**Comment by dplanella** [comment]
Current status:

```
$ sudo /snap/bin/etherpad-lite-unofficial.etherpad-lite 
+ cd /var/snap/etherpad-lite-unofficial/100001
+ exec /snap/etherpad-lite-unofficial/100001/bin/etherpad-lite --settings /snap/etherpad-lite-unofficial/100001/etc/settings.json
[2016-06-08 13:07:55.716] [WARN] console - DirtyDB is used. This is fine for testing but not recommended for production.
[2016-06-08 13:07:58.216] [ERROR] console - Failed to load '/snap/etherpad-lite-unofficial/100001/lib/node_modules/ep_etherpad-lite/node/hooks/express/static:expressCreateServer' for 'ep_etherpad-lite/static/hooks/expressCreateServer': Error: ENOENT: no such file or directory, stat '/snap/etherpad-lite-unofficial/100001/lib/var/'
```
- It seems something [in this module](https://github.com/ether/etherpad-lite/blob/develop/src/node/hooks/express/static.js) is trying to write to `$SNAP/lib/var`

Notes: as per the discussion on https://github.com/Winael/snappy-playpen-1/pull/1, we need to look at:

- asac's upstream branch at https://github.com/asac/etherpad-lite/commits/snap-support
- https://github.com/asac/etherpad-lite/commit/d3e12b31e4542eb637b33f2fbbad265d7116e38f
- https://github.com/asac/etherpad-lite/commit/8e62911cb2f6be278f70d11c2dc8492e22782f2a

**Comment by dholbach** [comment]
*[etherpad-lite/README.md, line 5 \[r6\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/32#-KKmY3aQM4lJ7nthchZQ:-KKmY3aR7SmF_go7wDcu:1185909849) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/03cdd460859890e7ec8e31d06bc411121a92f5de/etherpad-lite/README.md#L5)):*
> ```Markdown
> title: Etherpad-lite
> author: Winael
> status: WIP. Not working
> ```

We are still blocked here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/32)*

**Comment by Winael** [comment]
It seems that I have commit in the wrong place sorry ^^

**Pull request closed without merging**
