### PR TITLE
Upgrading wallpaperdownloader version to v2.1

### PR DESCRIPTION
**Pull request by egara**
New version 2.1 uploaded to the Ubuntu Store. Upgrading version within snapcraft.yaml
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/egara%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/13696843%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/204%23issuecomment-238203932%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-08-08T10%3A55%3A26Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/13696843%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/egara%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-08-08T10%3A57%3A40Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/13696843%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/egara%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20don%27t%20know%20what%20I%27m%20doing%20%3AP%5Cr%5CnI%20have%20approved%20the%20pull%20request%20using%20my%20github%20account%20but%20I%20don%27t%20know%20if%20this%20is%20the%20proper%20way%20to%20ask%20for%20a%20pull%20request.%20The%20mechanism%20has%20changed%20from%20the%20last%20time%20I%20asked%20for%20a%20pull%20request%2C%20sorry%21%21%22%2C%20%22created_at%22%3A%20%222016-08-08T11%3A00%3A35Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/13696843%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/egara%22%7D%7D%2C%20%7B%22body%22%3A%20%22Thanks.%20Merging.%20%3A-%29%22%2C%20%22created_at%22%3A%20%222016-08-09T07%3A05%3A54Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/ubuntu/snappy-playpen/pull/204%23issuecomment-238203932%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/204%23issuecomment-238204336%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/204%23issuecomment-238204828%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/204%23issuecomment-238471173%22%5D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/egara'></a>

- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/ubuntu/snappy-playpen/pull/204#issuecomment-238203932'>General Comment</a></b>
- <a href='https://github.com/egara'></a> :shipit:
- <a href='https://github.com/egara'></a> :shipit:
- <a href='https://github.com/egara'></a> I don't know what I'm doing :P
I have approved the pull request using my github account but I don't know if this is the proper way to ask for a pull request. The mechanism has changed from the last time I asked for a pull request, sorry!!
- <a href='https://github.com/dholbach'></a> Thanks. Merging. :-)

<a href='https://www.codereviewhub.com/ubuntu/snappy-playpen/pull/204?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/ubuntu/snappy-playpen/pull/204?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/ubuntu/snappy-playpen/pull/204?approve=0'></a>&nbsp;<a href='https://github.com/ubuntu/snappy-playpen/pull/204'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by didrocks** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/ubuntu/snappy-playpen/pull/204'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by egara** [comment]
:shipit:

**Comment by egara** [comment]
:shipit:

**Comment by egara** [comment]
I don't know what I'm doing :P
I have approved the pull request using my github account but I don't know if this is the proper way to ask for a pull request. The mechanism has changed from the last time I asked for a pull request, sorry!!

**Comment by dholbach** [comment]
Thanks. Merging. :-)

**Pull request merged**
