### PR TITLE
Add stage env

### PR DESCRIPTION
**Pull request by caldav**
Add stage packages after the vlc build, otherwise the vlc build fails.

### CODE REVIEW

**Comment by dholbach** [comment]
Nice work! :-)

**Comment by dplanella** [comment]
Looks good to me, the only issue that I noticed is that the path precedence does not quite work as expected: `/usr/bin` seems to be executed first.

    $ which vlc
    /usr/bin/vlc
    $ whereis vlc
    vlc: /usr/bin/vlc /usr/lib/vlc /usr/share/vlc /snap/bin/vlc /usr/share/man/man1/vlc.1.gz

**Comment by dholbach** [comment]
I think this is what's expected. Maybe @sergiusens or @kyrofa can comment?

**Comment by kyrofa** [comment]
@dholbach @dplanella I can't comment as to whether or not it's supposed to be that way, but yeah it's expected given the contents of /etc/profile.d/apps-bin-path.sh:

```bash
# Expand the $PATH to include /snap/bin which is what snappy applications
# use
PATH=$PATH:/snap/bin
```

**Pull request merged**
