### PR TITLE
Update the documentation for contributing to the Snappy Playpen

### PR DESCRIPTION
**Pull request by tsimonq2**
The CONTRIBUTING.md file doesn't actually show how to contribute. It only shows the requirements.

This pull request adds detailed instructions for contributing to the playpen.

---

This change is [Reviewable](https://reviewable.io/reviews/ubuntu/snappy-playpen/157)

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/ubuntu/snappy-playpen/pull/157%23issuecomment-231973344%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/157%23issuecomment-231973541%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/157%23issuecomment-231973608%22%2C%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/157%23issuecomment-231973695%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/ubuntu/snappy-playpen/pull/157%23issuecomment-231973344%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%5Cn%5Cn%5Cn%5CnReview%20status%3A%200%20of%201%20files%20reviewed%20at%20latest%20revision%2C%203%20unresolved%20discussions.%5Cn%5Cn---%5Cn%5Cn%2A%5BCONTRIBUTING.md%2C%20line%2030%20%5C%5C%5Br1%5C%5C%5D%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/157%23-KMTBsoMKyMZWvdbIUaP%3A-KMTBsoNzTQ_Hb5boT4k%3A-1421782242%29%20%28%5Braw%20file%5D%28https%3A//github.com/ubuntu/snappy-playpen/blob/a83f3c4253307ff9a3553857a8571411ebe0f00a/CONTRIBUTING.md%23L30%29%29%3A%2A%5Cn%3E%20%60%60%60Markdown%5Cn%3E%20%201.%20Run%20the%20following%20in%20a%20terminal%20to%20get%20the%20playpen%20source%3A%5Cn%3E%20%20%60git%20clone%20https%3A//github.com/ubuntu/snappy-playpen.git%60.%5Cn%3E%20%202.%20Go%20into%20the%20source%3A%20%60cd%20snappy-playpen%60.%5Cn%3E%20%60%60%60%5Cn%5CnI%27d%20say%20%5C%22change%20into%20the%20source%20directory%5C%22%20or%20something.%5Cn%5Cn---%5Cn%5Cn%2A%5BCONTRIBUTING.md%2C%20line%2031%20%5C%5C%5Br1%5C%5C%5D%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/157%23-KMTDT9Gk0cKN8inVmei%3A-KMTDT9HQJdz7XckPG0S%3A-349893190%29%20%28%5Braw%20file%5D%28https%3A//github.com/ubuntu/snappy-playpen/blob/a83f3c4253307ff9a3553857a8571411ebe0f00a/CONTRIBUTING.md%23L31%29%29%3A%2A%5Cn%3E%20%60%60%60Markdown%5Cn%3E%20%20%60git%20clone%20https%3A//github.com/ubuntu/snappy-playpen.git%60.%5Cn%3E%20%202.%20Go%20into%20the%20source%3A%20%60cd%20snappy-playpen%60.%5Cn%3E%20%203.%20Create%20a%20git%20branch%20for%20your%20snap%3A%20%60git%20checkout%20-b%20foo%60.%5Cn%3E%20%60%60%60%5Cn%5CnMaybe%20say%20%5C%22If%20you%20want%20to%20add%20a%20snap%20to%20the%20Snappy%20Playpen%2C%20...%5C%22%3F%5Cn%5Cn---%5Cn%5Cn%2A%5BCONTRIBUTING.md%2C%20line%2040%20%5C%5C%5Br1%5C%5C%5D%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/157%23-KMTDjepWY5ODjSbcN3K%3A-KMTDjepWY5ODjSbcN3L%3A-2128925136%29%20%28%5Braw%20file%5D%28https%3A//github.com/ubuntu/snappy-playpen/blob/a83f3c4253307ff9a3553857a8571411ebe0f00a/CONTRIBUTING.md%23L40%29%29%3A%2A%5Cn%3E%20%60%60%60Markdown%5Cn%3E%20%20%60%7C%20%3Awhite_check_mark%3A%20%20%7C%20%60foo%60%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%60.%5Cn%3E%20%2010.%20Add%20the%20files%20you%20edited/created%3A%20%60git%20add%20README.md%20foo/%60.%5Cn%3E%20%2011.%20Commit%20the%20files%3A%20%60git%20commit%20-a%60.%5Cn%3E%20%60%60%60%5Cn%5CnIf%20you%20use%20%60git%20commit%20-a%60%2C%20you%20only%20need%20to%20%60git%20add%60%20newly-created%20files%20in%20the%20step%20before.%5Cn%5Cn---%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/157%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-07-12T08%3A31%3A59Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%2C%20%7B%22body%22%3A%20%22Nice%20work.%20Maybe%20it%27d%20help%20to%20split%20up%20%5C%22working%20with%20git%20and%20Snappy%20Playpen%5C%22%20and%20%5C%22adding%20a%20new%20snap%5C%22%3F%20That%20way%20the%20list%20won%27t%20be%20as%20long%20and%20people%20who%20are%20looking%20to%20just%20fix%20something%20can%20do%20that%20as%20well.%5Cn%5Cn---%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/157%23-%3A-KMTE-ttm2DvXC5_9Ktg%3A-1898189744%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-07-12T08%3A32%3A55Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%2C%20%7B%22body%22%3A%20%22Can%20you%20check%20if%20any%20of%20the%20links%20mentioned%20in%20https%3A//reviewable.io/reviews/ubuntu/snappy-playpen/152%20make%20sense%3F%5Cn%5Cn---%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/ubuntu/snappy-playpen/157%23-%3A-KMTEEVra-5WDj4be_-S%3A16259223%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-07-12T08%3A33%3A15Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1346979%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dholbach%22%7D%7D%2C%20%7B%22body%22%3A%20%22Will%20do%2C%20thanks%20Daniel.%20%3A%29%22%2C%20%22created_at%22%3A%20%222016-07-12T08%3A33%3A39Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3689821%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tsimonq2%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/ubuntu/snappy-playpen/pull/157#issuecomment-231973344'>General Comment</a></b>
## \- <a href='https://github.com/dholbach'></a> Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

_[CONTRIBUTING.md, line 30 [r1]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/157#-KMTBsoMKyMZWvdbIUaP:-KMTBsoNzTQ_Hb5boT4k:-1421782242) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/a83f3c4253307ff9a3553857a8571411ebe0f00a/CONTRIBUTING.md#L30)):_

> ``` Markdown
>  1. Run the following in a terminal to get the playpen source:
>  `git clone https://github.com/ubuntu/snappy-playpen.git`.
>  2. Go into the source: `cd snappy-playpen`.
> ```
> ## I'd say "change into the source directory" or something.
> 
> _[CONTRIBUTING.md, line 31 [r1]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/157#-KMTDT9Gk0cKN8inVmei:-KMTDT9HQJdz7XckPG0S:-349893190) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/a83f3c4253307ff9a3553857a8571411ebe0f00a/CONTRIBUTING.md#L31)):_
> 
> ``` Markdown
>  `git clone https://github.com/ubuntu/snappy-playpen.git`.
>  2. Go into the source: `cd snappy-playpen`.
>  3. Create a git branch for your snap: `git checkout -b foo`.
> ```
> ## Maybe say "If you want to add a snap to the Snappy Playpen, ..."?
> 
> _[CONTRIBUTING.md, line 40 [r1]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/157#-KMTDjepWY5ODjSbcN3K:-KMTDjepWY5ODjSbcN3L:-2128925136) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/a83f3c4253307ff9a3553857a8571411ebe0f00a/CONTRIBUTING.md#L40)):_
> 
> ``` Markdown
>  `| :white_check_mark:  | `foo`              |                           |`.
>  10. Add the files you edited/created: `git add README.md foo/`.
>  11. Commit the files: `git commit -a`.
> ```
> ## If you use `git commit -a`, you only need to `git add` newly-created files in the step before.
> 
> _Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/157)_
> 
> 
> ## \- <a href='https://github.com/dholbach'></a> Nice work. Maybe it'd help to split up "working with git and Snappy Playpen" and "adding a new snap"? That way the list won't be as long and people who are looking to just fix something can do that as well.
> 
> _Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/157#-:-KMTE-ttm2DvXC5_9Ktg:-1898189744)_
> 
> 
> ## \- <a href='https://github.com/dholbach'></a> Can you check if any of the links mentioned in https://reviewable.io/reviews/ubuntu/snappy-playpen/152 make sense?
> 
> _Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/157#-:-KMTEEVra-5WDj4be_-S:16259223)_
> 
> 
> - <a href='https://github.com/tsimonq2'></a> Will do, thanks Daniel. :)

<a href='https://www.codereviewhub.com/ubuntu/snappy-playpen/pull/157?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/ubuntu/snappy-playpen/pull/157?approve=1'></a>&nbsp;<a href='https://github.com/ubuntu/snappy-playpen/pull/157'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dholbach** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[CONTRIBUTING.md, line 30 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/157#-KMTBsoMKyMZWvdbIUaP:-KMTBsoNzTQ_Hb5boT4k:-1421782242) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/a83f3c4253307ff9a3553857a8571411ebe0f00a/CONTRIBUTING.md#L30)):*
> ```Markdown
>  1. Run the following in a terminal to get the playpen source:
>  `git clone https://github.com/ubuntu/snappy-playpen.git`.
>  2. Go into the source: `cd snappy-playpen`.
> ```

I'd say "change into the source directory" or something.

---

*[CONTRIBUTING.md, line 31 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/157#-KMTDT9Gk0cKN8inVmei:-KMTDT9HQJdz7XckPG0S:-349893190) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/a83f3c4253307ff9a3553857a8571411ebe0f00a/CONTRIBUTING.md#L31)):*
> ```Markdown
>  `git clone https://github.com/ubuntu/snappy-playpen.git`.
>  2. Go into the source: `cd snappy-playpen`.
>  3. Create a git branch for your snap: `git checkout -b foo`.
> ```

Maybe say "If you want to add a snap to the Snappy Playpen, ..."?

---

*[CONTRIBUTING.md, line 40 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/157#-KMTDjepWY5ODjSbcN3K:-KMTDjepWY5ODjSbcN3L:-2128925136) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/a83f3c4253307ff9a3553857a8571411ebe0f00a/CONTRIBUTING.md#L40)):*
> ```Markdown
>  `| :white_check_mark:  | `foo`              |                           |`.
>  10. Add the files you edited/created: `git add README.md foo/`.
>  11. Commit the files: `git commit -a`.
> ```

If you use `git commit -a`, you only need to `git add` newly-created files in the step before.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/157)*

**Comment by dholbach** [comment]
Nice work. Maybe it'd help to split up "working with git and Snappy Playpen" and "adding a new snap"? That way the list won't be as long and people who are looking to just fix something can do that as well.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/157#-:-KMTE-ttm2DvXC5_9Ktg:-1898189744)*

**Comment by dholbach** [comment]
Can you check if any of the links mentioned in https://reviewable.io/reviews/ubuntu/snappy-playpen/152 make sense?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/157#-:-KMTEEVra-5WDj4be_-S:16259223)*

**Comment by tsimonq2** [comment]
Will do, thanks Daniel. :)

**Pull request closed without merging**
