### PR TITLE
Wallpaperdownloader pull request

### PR DESCRIPTION
**Pull request by egara**
Updating wallpaperdownloader to version 2.2

### CODE REVIEW

**Comment by egara** [comment]
Upsss build failed.

Any idea?

`7'ascii' codec can't encode character '\u29f8' in position 24: ordinal not in range(128)

ls: cannot access *.snap: No such file or directory

FAILURE: No .snap file built`

**Comment by egara** [comment]
I don't know why it is failing. It is building fine under Ubuntu 16.04 and "native" snapcraft version 2.16

**Comment by dholbach** [comment]
Can you change `[desktop/gtk3]` to `[desktop-gtk3]`?

**Comment by egara** [comment]
@dholbach thanks! It worked!! ;)

**Comment by dholbach** [comment]
Great work!

**Pull request merged**
